package com.example.vocab

/** Original teaching definitions/examples; Cambridge Dictionary links document usage checks. */
enum class LexicalRelationType { NEAR_SYNONYM, REGISTER, COLLOCATION, GRAMMAR, USAGE }

data class LexicalSense(val word: String, val partOfSpeech: String, val definition: String,
    val meaningFa: String, val example: String, val index: Int)

data class LexicalRelation(val id: String, val first: LexicalSense, val second: LexicalSense,
    val type: LexicalRelationType, val firstPrompt: String, val secondPrompt: String,
    val firstAnswers: Set<String>, val secondAnswers: Set<String>, val noteFa: String,
    val sources: List<String>, val version: Int = 1,
    val contentLicense: String = "Original LinguaFa teaching text") {
    fun sense(word: String) = if (word.equals(first.word, true)) first else second
    fun partner(word: String) = if (word.equals(first.word, true)) second else first
    fun prompt(word: String) = if (word.equals(first.word, true)) firstPrompt else secondPrompt
    fun answers(word: String) = if (word.equals(first.word, true)) firstAnswers else secondAnswers
}

object LexicalBank {
    private fun relation(index: Int, a: String, b: String, type: LexicalRelationType,
        da: String, db: String, posa: String, posb: String, ma: String, mb: String,
        pa: String, pb: String, note: String, sharedA: Boolean, sharedB: Boolean): LexicalRelation = LexicalRelation(
        "$a-$b", LexicalSense(a, posa, da, ma, pa.replace("____", a), 10_000 + index * 2),
        LexicalSense(b, posb, db, mb, pb.replace("____", b), 10_001 + index * 2), type, pa, pb,
        if (sharedA) setOf(a,b) else setOf(a), if (sharedB) setOf(a,b) else setOf(b), note,
        listOf("https://dictionary.cambridge.org/dictionary/english/$a", "https://dictionary.cambridge.org/dictionary/english/$b"))

    val relations: List<LexicalRelation> = listOf(
        relation(1, "avoid", "prevent", LexicalRelationType.USAGE, "keep away from an unwanted situation", "stop something from happening", "verb", "verb", "دوری کردن", "جلوگیری کردن", "I left early to ____ the rush-hour traffic.", "The new safety checks may ____ serious accidents.", "avoid یعنی از چیزی دوری کردن؛ prevent یعنی جلوی رخ‌دادن چیزی را گرفتن.", false, false),
        relation(2, "economic", "economical", LexicalRelationType.USAGE, "connected with the economy", "using little money or resources", "adjective", "adjective", "اقتصادی", "به‌صرفه", "The report examines the country's ____ growth.", "This small car is cheap and ____ to run.", "economic یعنی مربوط به اقتصاد؛ economical یعنی کم‌هزینه و به‌صرفه.", false, false),
        relation(3, "say", "tell", LexicalRelationType.USAGE, "express spoken words", "give someone information in words", "verb", "verb", "گفتن", "به کسی گفتن", "What did the witness ____ about the accident?", "Please ____ me the truth.", "say معمولاً روی خودِ گفته تمرکز دارد؛ tell معمولاً شنونده یا چیزی را که گفته می‌شود هم می‌گیرد.", false, false),
        relation(4, "borrow", "lend", LexicalRelationType.USAGE, "take something temporarily and return it", "give something temporarily expecting it back", "verb", "verb", "قرض گرفتن", "قرض دادن", "Could I ____ your pen for a minute?", "Can you ____ me your pen for a minute?", "borrow یعنی قرض گرفتن؛ lend یعنی قرض دادن.", false, false),
        relation(5, "rise", "raise", LexicalRelationType.USAGE, "move upward without a direct object", "move something to a higher level", "verb", "verb", "بالا رفتن", "بالا بردن", "Prices often ____ during the holiday season.", "The company plans to ____ its prices next month.", "rise یعنی خودِ چیزی بالا برود؛ raise یعنی کسی یا چیزی آن را بالا ببرد.", false, false),
        relation(6, "remember", "remind", LexicalRelationType.USAGE, "bring something back to your own memory", "make another person think of something again", "verb", "verb", "به یاد آوردن", "یادآوری کردن به کسی", "I must ____ to call the dentist.", "Please ____ me to call the dentist.", "remember یعنی به خاطر آوردن؛ remind یعنی چیزی را به یادِ کسی انداختن.", false, false),
        relation(7, "affect", "effect", LexicalRelationType.USAGE, "change or influence something", "a change produced by a cause", "verb", "noun", "تأثیر گذاشتن", "اثر یا نتیجه", "Lack of sleep can ____ your concentration.", "The new policy had an immediate ____ on prices.", "affect معمولاً فعلِ «تأثیر گذاشتن» است؛ effect معمولاً اسمِ «تأثیر یا نتیجه» است.", false, false),
        relation(8, "advice", "advise", LexicalRelationType.USAGE, "a suggestion about what someone should do", "offer a suggestion about what to do", "noun", "verb", "توصیه", "توصیه کردن", "Could you give me some ____?", "I would ____ you to check the figures.", "advice اسم و به‌معنی توصیه است؛ advise فعل و به‌معنی توصیه کردن است.", false, false),
        relation(9, "accept", "except", LexicalRelationType.USAGE, "agree to receive or approve something", "excluding someone or something", "verb", "preposition", "پذیرفتن", "به‌جز", "She decided to ____ the job offer.", "Everyone came ____ Ali.", "accept یعنی پذیرفتن؛ except در این جمله یعنی به‌جز.", false, false),
        relation(10, "lose", "loose", LexicalRelationType.USAGE, "no longer have or be able to find something", "not firmly attached or tight", "verb", "adjective", "گم کردن", "شل", "Be careful not to ____ your keys.", "This screw is ____; it needs tightening.", "lose یعنی گم‌کردن یا از دست‌دادن؛ loose یعنی شل یا گشاد.", false, false),
        relation(11, "do", "make", LexicalRelationType.USAGE, "perform an activity or task", "create or produce a result", "verb", "verb", "انجام دادن", "ایجاد کردن", "I need to ____ my homework before dinner.", "They had to ____ a difficult decision.", "do با فعالیت‌هایی مثل تکلیف می‌آید؛ make با ساختن یا ایجادکردن نتیجه‌ای مثل تصمیم.", false, false),
        relation(12, "discover", "invent", LexicalRelationType.USAGE, "find something that already exists but was unknown", "create something new that did not exist before", "verb", "verb", "کشف کردن", "اختراع کردن", "Scientists hope to ____ a new planet.", "She hopes to ____ a tool that saves water.", "discover یعنی چیزی را که از قبل وجود دارد کشف‌کردن؛ invent یعنی چیزی تازه اختراع‌کردن.", false, false),
        relation(13, "begin", "start", LexicalRelationType.REGISTER, "enter the first part of an activity", "make an activity or machine operate", "verb", "verb", "آغاز کردن", "شروع کردن", "The course will ____ on Monday.", "Press the switch to ____ the engine.", "begin و start برای شروع فعالیت نزدیک‌اند؛ begin رسمی‌تر است. برای روشن‌کردن موتور، start به کار می‌رود.", true, false),
        relation(14, "finish", "end", LexicalRelationType.NEAR_SYNONYM, "complete an activity or task", "reach or bring something to a stopping point", "verb", "verb", "تمام کردن کار", "پایان یافتن یا پایان دادن", "The class will ____ at noon.", "The ceremony will ____ before sunset.", "finish بیشتر روی کامل‌شدن کار تمرکز دارد؛ end روی پایان‌رسیدن. در این دو جمله هر دو ممکن‌اند.", true, true),
        relation(15, "big", "large", LexicalRelationType.COLLOCATION, "of considerable size, importance or extent", "of considerable size or amount", "adjective", "adjective", "بزرگ یا مهم", "بزرگ از نظر اندازه یا مقدار", "Buying a home is a ____ decision.", "In this formal report, use the standard collocation: a ____ number of respondents.", "big در گفتار و اهمیتِ موضوع رایج است؛ large در مقدار و آمار رسمی، مثل large number، طبیعی‌تر است.", false, false),
        relation(16, "small", "little", LexicalRelationType.GRAMMAR, "limited in size, number or amount", "small, or limited in amount before an uncountable noun", "adjective", "determiner", "کوچک یا کم", "کوچک یا مقدار کم", "The survey used a ____ number of participants.", "We have ____ time before the train leaves.", "small صفت اندازه است؛ little برای مقدار کمِ اسم غیرقابل‌شمارش مثل time هم استفاده می‌شود.", false, false),
        relation(17, "fast", "quick", LexicalRelationType.COLLOCATION, "deeply or firmly, in fixed expressions such as fast asleep", "taking only a short time", "adverb", "adjective", "عمیق در ترکیب خواب عمیق", "سریع از نظر مدت", "The child is ____ asleep.", "Could we have a ____ conversation before lunch?", "fast asleep یک ترکیب ثابت است؛ quick معمولاً برای کار یا رویداد کوتاه، مثل quick conversation، مناسب است.", false, false),
        relation(18, "job", "work", LexicalRelationType.GRAMMAR, "a particular paid position or assigned task", "activity requiring effort, often to earn money", "noun", "noun", "شغل یا وظیفهٔ مشخص", "کار و فعالیت", "She applied for a new ____ at the bank.", "There is a lot of ____ to complete today.", "job قابل‌شمارش است؛ work در معنای کار معمولاً غیرقابل‌شمارش است. a job ولی some work.", false, false),
        relation(19, "buy", "purchase", LexicalRelationType.REGISTER, "obtain something by paying for it", "obtain something by paying, often in formal language", "verb", "verb", "خریدن", "خریداری کردن", "We plan to ____ new office chairs.", "The company will ____ new equipment.", "buy واژهٔ عمومی است؛ purchase در متن رسمی و تجاری رایج‌تر است. در این جمله‌ها هر دو درست‌اند.", true, true),
        relation(20, "help", "assist", LexicalRelationType.REGISTER, "make it easier for someone to do something", "help someone, often in formal or professional situations", "verb", "verb", "کمک کردن", "یاری کردن در کاربرد رسمی", "Could you ____ me with this application?", "A trained adviser can ____ you with the forms.", "assist از help رسمی‌تر است. هر دو با someone with something می‌آیند و اینجا هر دو پذیرفته‌اند.", true, true),
        relation(21, "need", "require", LexicalRelationType.REGISTER, "have to have something for a purpose", "need something, often as a rule or condition", "verb", "verb", "نیاز داشتن", "نیاز داشتن یا لازم دانستن", "These plants ____ regular watering.", "All applicants ____ a valid passport.", "require در دستور، شرط و متن رسمی بیشتر دیده می‌شود؛ need عمومی‌تر است. این جمله‌ها هر دو را می‌پذیرند.", true, true),
        relation(22, "choose", "select", LexicalRelationType.REGISTER, "decide which person or thing you want", "choose a person or thing from available options", "verb", "verb", "انتخاب کردن", "برگزیدن از گزینه‌ها", "Please ____ one of the available dates.", "You may ____ any topic from the list.", "select معمولاً انتخاب از فهرست یا مجموعه را برجسته می‌کند؛ choose عمومی‌تر است. هر دو اینجا مناسب‌اند.", true, true),
        relation(23, "mistake", "error", LexicalRelationType.REGISTER, "an action or judgement that is wrong", "something incorrect, often in technical or formal contexts", "noun", "noun", "اشتباه", "خطا", "He made a serious ____ in the calculation.", "The report contains a factual ____.", "error در گزارش و محاسبات رسمی رایج‌تر است؛ mistake عمومی‌تر و برای تصمیم نادرست هم کاربرد دارد.", true, true),
        relation(24, "allow", "permit", LexicalRelationType.REGISTER, "let someone do something", "allow something, often officially", "verb", "verb", "اجازه دادن", "اجازه دادن رسمی", "The rules ____ visitors to take photographs.", "The licence will ____ the business to operate.", "permit معمولاً رسمی‌تر و مرتبط با مجوز است؛ allow عمومی‌تر است. هر دو با object + to-infinitive می‌آیند.", true, true),
        relation(25, "show", "demonstrate", LexicalRelationType.REGISTER, "make something visible or explain how it is done", "show clearly by evidence or a practical example", "verb", "verb", "نشان دادن", "نشان دادن روشن با مثال یا شواهد", "The trainer will ____ how to use the device.", "These results ____ the benefits of regular practice.", "demonstrate توضیح روشن، نمایش عملی یا شواهد را برجسته می‌کند؛ show گسترده‌تر است. در این کاربردها هر دو ممکن‌اند.", true, true),
        relation(26, "important", "significant", LexicalRelationType.USAGE, "having value or a strong effect on what matters", "noticeable or meaningful; unlikely to be explained by chance in statistics", "adjective", "adjective", "مهم", "معنادار یا قابل‌توجه", "This change is ____ for patient safety.", "The difference was statistically ____.", "important اهمیت را می‌رساند؛ significant در آمار معنی تخصصی دارد و statistically significant با important جایگزین نمی‌شود.", true, false),
        relation(27, "improve", "enhance", LexicalRelationType.NEAR_SYNONYM, "make something better or become better", "increase the quality, value or attractiveness of something", "verb", "verb", "بهتر کردن یا بهتر شدن", "ارتقا دادن کیفیت یا ارزش", "The course should ____ your writing skills.", "Better lighting can ____ the quality of the photographs.", "improve عمومی است و می‌تواند بدون مفعول هم بیاید؛ enhance معمولاً مفعول می‌گیرد و رسمی‌تر است. این دو مثال هر دو را می‌پذیرند.", true, true),
        relation(28, "chance", "opportunity", LexicalRelationType.USAGE, "a possibility of an event, or an occasion to do something", "a favourable occasion to do something", "noun", "noun", "احتمال یا فرصت", "فرصت برای انجام کار", "There is a high ____ of rain tonight.", "The internship offers an ____ to gain experience.", "chance می‌تواند احتمال باشد؛ opportunity موقعیت انجام کار است. در معنای فرصت هم‌پوشانی دارند، ولی احتمال باران opportunity نیست.", false, false),
        relation(29, "speak", "talk", LexicalRelationType.USAGE, "use words orally, including using a language", "have a conversation or discuss something", "verb", "verb", "صحبت کردن یا به زبانی سخن گفتن", "گفت‌وگو کردن", "Can you ____ Arabic?", "Can we ____ about the plan after lunch?", "speak برای تواناییِ صحبت‌کردن به یک زبان به کار می‌رود؛ talk بیشتر گفت‌وگو را برجسته می‌کند. در گفت‌وگو هر دو گاهی مناسب‌اند.", false, true),
        relation(30, "ensure", "assure", LexicalRelationType.GRAMMAR, "make certain that something happens or is true", "tell someone confidently that something is true", "verb", "verb", "اطمینان حاصل کردن", "به کسی اطمینان دادن", "Please ____ that the door is locked.", "I can ____ you that the documents are safe.", "ensure روی محقق‌شدن نتیجه است؛ assure معمولاً شخص را به عنوان مفعول می‌گیرد: assure someone that ... .", false, false),
        relation(31, "adapt", "adopt", LexicalRelationType.USAGE, "change to suit a new situation", "take up a practice, idea or method as your own", "verb", "verb", "سازگار کردن یا شدن", "پذیرفتن و به کار گرفتن", "We must ____ to the colder climate.", "The school will ____ a new teaching method.", "adapt یعنی سازگارشدن یا تغییر برای شرایط؛ adopt یعنی پذیرفتن روش یا ایده و به‌کارگرفتن آن.", false, false),
        relation(32, "efficient", "effective", LexicalRelationType.USAGE, "working well without wasting time or resources", "producing the intended result", "adjective", "adjective", "کارا و کم‌اتلاف", "مؤثر و نتیجه‌بخش", "This process is ____ because it uses very little energy.", "The treatment is ____ because it achieves the intended result.", "efficient روی کم‌اتلاف‌بودنِ منابع تأکید دارد؛ effective روی رسیدن به نتیجه. چیزی می‌تواند مؤثر باشد ولی منابع زیادی مصرف کند.", false, false),
        relation(33, "sensible", "sensitive", LexicalRelationType.USAGE, "showing practical judgement", "easily affected by feelings, changes or substances", "adjective", "adjective", "عاقلانه و سنجیده", "حساس", "Saving some money for emergencies is ____.", "My skin is ____ to this soap.", "sensible یعنی سنجیده و عاقلانه؛ sensitive یعنی حساس. sensitive to برای حساسیت به چیزی به کار می‌رود.", false, false),
        relation(34, "historic", "historical", LexicalRelationType.USAGE, "important because it changes or marks history", "connected with events or information from the past", "adjective", "adjective", "تاریخ‌ساز یا مهم در تاریخ", "مربوط به تاریخ", "The peace agreement was a ____ turning point.", "The researcher checked the ____ records.", "historic اهمیت تاریخی را برجسته می‌کند؛ historical صرفاً مربوط به گذشته و تاریخ است.", false, false),
        relation(35, "especially", "specially", LexicalRelationType.USAGE, "particularly or more than the other things mentioned", "for a particular purpose", "adverb", "adverb", "به‌ویژه", "برای هدفی خاص", "I enjoy outdoor activities, ____ hiking.", "This tool was designed ____ for left-handed users.", "especially معمولاً به‌ویژه است؛ specially هدف خاص را برجسته می‌کند. در کاربرد هدف خاص هم‌پوشانی دارند، پس هر دو پاسخ پذیرفته‌اند.", false, true),
        relation(36, "imply", "infer", LexicalRelationType.USAGE, "suggest something without stating it directly", "reach a conclusion from evidence or clues", "verb", "verb", "تلویحاً رساندن", "از شواهد استنباط کردن", "What does the author ____ by that remark?", "What can the reader ____ from these facts?", "گوینده یا متن imply می‌کند؛ شنونده یا خواننده infer می‌کند. جهت انتقال معنا و استنتاج فرق دارد.", false, false)
    )
    val words: Set<String> = relations.flatMap { listOf(it.first.word, it.second.word) }.toSet()
    fun forWord(word: String, knownWords: Set<String>? = null): LexicalRelation? = relations.firstOrNull {
        (word.equals(it.first.word, true) || word.equals(it.second.word, true)) &&
            (knownWords == null || it.partner(word).word in knownWords)
    }
}
