package com.example.data.seed

import com.example.data.model.ListeningExercise
import com.example.data.model.ListeningQuestion
import com.example.data.model.ReadingPassage
import com.example.data.model.ReadingQuestion

object ReadingListeningSeed {
    fun getReadingPassages(): List<ReadingPassage> = listOf(
        ReadingPassage(
            id = "reading_renewable_economics",
            titleEn = "The Economics of Renewable Energy Transition",
            titleFa = "اقتصاد گذار به انرژی‌های تجدیدپذیر",
            topic = "Economics & Environment",
            level = "B2-C1",
            exam = "IELTS Academic",
            contentEn = """Over the past two decades, the global energy matrix has begun undergoing a fundamental transformation. What was once considered an idealistic environmental aspiration has evolved into a viable economic proposition. The levelized cost of electricity (LCOE) generated by solar photovoltaic and onshore wind installations has plummeted by more than eighty percent since 2010, outcompeting conventional fossil fuel generation in numerous competitive markets.

However, this transition is not without formidable infrastructural constraints. Traditional power grids were originally designed around centralized, predictable baseload generation. In contrast, solar and wind energy sources are inherently intermittent, fluctuating with meteorological conditions. To mitigate these disparities, grid operators must integrate advanced battery storage solutions, demand-response management systems, and smart grid automation. 

Furthermore, substantial capital allocation is required to overhaul cross-border transmission networks. Policymakers must adopt pragmatic regulatory frameworks that incentivize private investment while safeguarding social welfare against acute tariff volatility.""",
            summaryFa = "این متن روند کاهش شدید هزینه‌های تولید برق خورشیدی و بادی را در دو دهه اخیر بررسی کرده و چالش‌های شبکه برق به دلیل نوسان‌پذیری این انرژی‌ها و لزوم سرمایه‌گذاری در باتری‌ها و اصلاح قوانین را توضیح می‌دهد.",
            questions = listOf(
                ReadingQuestion(
                    id = "rq1_1",
                    questionEn = "What has driven the economic viability of solar and wind energy since 2010?",
                    options = listOf(
                        "An 80% decrease in the levelized cost of electricity",
                        "Government mandates forbidding all fossil fuels",
                        "A decrease in consumer demand for electricity",
                        "The total elimination of weather fluctuations"
                    ),
                    correctIndex = 0,
                    explanationFa = "در پاراگراف اول صراحتاً بیان شده که هزینه هم‌تراز شده برق (LCOE) خورشیدی و بادی بیش از ۸۰ درصد کاهش یافته است."
                ),
                ReadingQuestion(
                    id = "rq1_2",
                    questionEn = "Why do renewable sources pose a challenge to traditional power grids?",
                    options = listOf(
                        "Because they are too centralized in one location",
                        "Because their generation is intermittent and fluctuates with weather",
                        "Because they consume more water than coal plants",
                        "Because battery storage cannot be utilized"
                    ),
                    correctIndex = 1,
                    explanationFa = "پاراگراف دوم توضیح می‌دهد که انرژی خورشیدی و بادی به طور ذاتی ناپیوسته (intermittent) بوده و با شرایط آب‌وهوا نوسان می‌کند."
                )
            )
        ),
        ReadingPassage(
            id = "reading_bilingualism",
            titleEn = "Cognitive Architecture and Bilingualism",
            titleFa = "معماری شناختی و دوزبانگی",
            topic = "Psychology & Neuroscience",
            level = "C1",
            exam = "TOEFL Academic",
            contentEn = """For much of the twentieth century, educational authorities warned that rearing children in a multilingual environment could induce cognitive confusion and impair linguistic development. Contemporary neuroscience has thoroughly refuted this obsolete misconception. Empirical studies demonstrate that the bilingual brain develops enhanced executive control mechanisms.

Because both linguistic systems remain perpetually active in a bilingual individual, the brain must continuously recruit executive control networks to inhibit intrusive words from the unintended language. This constant mental gymnastics strengthens the prefrontal cortex, enhancing attentional control, working memory, and cognitive flexibility. 

Moreover, epidemiological research indicates that lifelong bilingualism builds cognitive reserve, delaying the onset of Alzheimer's disease symptoms by four to five years compared to monolingual peers.""",
            summaryFa = "این مقاله نظریه منسوخ قدیمی مبنی بر سردرگمی ذهنی کودکان دوزبانه را رد کرده و نشان می‌دهد که فعال بودن همزمان دو زبان در مغز، بخش کورتکس پیش‌پیشانی را تقویت کرده و بروز علائم آلزایمر را ۴ تا ۵ سال به تعویق می‌اندازد.",
            questions = listOf(
                ReadingQuestion(
                    id = "rq2_1",
                    questionEn = "What obsolete twentieth-century belief about bilingualism does the author mention?",
                    options = listOf(
                        "That it accelerates dementia onset",
                        "That it causes mental confusion and impairs language development",
                        "That it is only possible before age five",
                        "That it harms physical hearing organs"
                    ),
                    correctIndex = 1,
                    explanationFa = "متن در ابتدا اشاره می‌کند که در قرن بیستم تصور می‌شد دوزبانگی موجب سردرگمی شناختی و اختلال در تکامل زبان می‌شود."
                )
            )
        )
    )

    fun getListeningExercises(): List<ListeningExercise> = listOf(
        ListeningExercise(
            id = "listening_coral_bleaching",
            titleEn = "Marine Biology: Coral Bleaching Mechanisms",
            titleFa = "زیست‌شناسی دریا: سازوکارهای سفیدشدگی مرجان‌ها",
            topic = "Marine Biology",
            level = "B2-C1",
            exam = "TOEFL Academic Talk",
            audioScriptEn = "Good morning class. Today we are examining the physiological breakdown between reef-building corals and their symbiotic photosynthetic algae, known as zooxanthellae. Under normal conditions, these microscopic dinoflagellates reside inside the gastrodermal cells of the coral polyps, providing up to ninety percent of the host's daily metabolic energy via photosynthesis. In return, the coral provides sheltered habitat and essential nutrients like nitrogen and carbon dioxide. However, when thermal stress elevates sea surface temperatures by even one or two degrees Celsius above historical averages for prolonged weeks, this mutualistic partnership collapses. The algae begin producing reactive oxygen species that damage the coral tissue. To protect itself from internal cellular toxicity, the coral host is compelled to expel the algae. Deprived of their symbiotic partners and photosynthetic pigments, the calcified coral skeletons turn stark white. Unless ocean temperatures normalize swiftly, the corals starve and succumb to bacterial pathogens.",
            transcriptFa = "صبح همگی بخیر. امروز به بررسی گسست فیزیولوژیک میان مرجان‌های صخره‌ساز و جلبک‌های همزیست آنها (زئوگزانتلا) می‌پردازیم. این جلبک‌ها تا ۹۰ درصد انرژی متابولیک مرجان را با فتوسنتز تامین می‌کنند. اما هنگامی که استرس حرارتی دمای آب دریا را حتی ۱ یا ۲ درجه بالاتر از میانگین ببرد، این همکاری مشترک فرو می‌پاشد و مرجان ناچار می‌شود جلبک‌ها را به بیرون براند...",
            questions = listOf(
                ListeningQuestion(
                    id = "lq1_1",
                    questionEn = "What happens to the relationship between corals and algae during thermal stress?",
                    options = listOf(
                        "The algae produce toxic reactive oxygen species and are expelled",
                        "The coral moves to deeper oceanic trenches",
                        "The algae double their photosynthetic output",
                        "The coral consumes the algae as a food source"
                    ),
                    correctIndex = 0,
                    explanationFa = "در فایل صوتی تصریح می‌شود که جلبک‌ها در اثر تنش حرارتی ترکیبات اکسیژن فعال تولید کرده و مرجان ناچار به دفع آنها می‌شود."
                )
            )
        ),
        ListeningExercise(
            id = "listening_campus_housing",
            titleEn = "Campus Life: Apartment Lease Discussion",
            titleFa = "زندگی دانشجویی: گفتگو پیرامون اجاره‌نامه خوابگاه",
            topic = "Campus Life & Housing",
            level = "B1-B2",
            exam = "TOEFL Daily Life & IELTS Sec 1",
            audioScriptEn = "Hi Sarah, thanks for coming in. I reviewed your student housing transfer request. While we do have a studio apartment opening up next to the science quad, the tenancy agreement stipulates a twelve-month minimum commitment. If you plan to participate in the overseas study exchange program during the spring semester, you would need to arrange an authorized sublease, or else pay a cancellation fee equal to two months' rent.",
            transcriptFa = "سلام سارا، ممنون از مراجعه‌ات. من درخواست جابجایی مسکن دانشجویی شما را بررسی کردم. هرچند یک آپارتمان سوئیت در مجاورت دانشکده علوم در حال خالی شدن است، اما قرارداد اجاره مستلزم تعهد حداقل دوازده ماهه است...",
            questions = listOf(
                ListeningQuestion(
                    id = "lq2_1",
                    questionEn = "What condition must Sarah fulfill if she leaves for study abroad in spring?",
                    options = listOf(
                        "Sublease the room authorizedly or pay a two-month cancellation penalty",
                        "Forfeit her university scholarship immediately",
                        "Move into a dormitory triple room",
                        "Extend her lease to twenty-four months"
                    ),
                    correctIndex = 0,
                    explanationFa = "مسئول مسکن تصریح کرد که در صورت عزیمت به فرصت مطالعاتی یا باید ساب‌لیز مجاز هماهنگ شود یا جریمه دو ماه اجاره پرداخت گردد."
                )
            )
        )
    )
}
