#!/usr/bin/env python3
"""Curated academic discourse and hedging expressions for IELTS and TOEFL.

These are the fixed phrases that separate a Band 6 answer from a Band 8 one:
hedging claims, framing arguments, and signposting causation. They are recorded
as `idiom` because the validator's noun/adjective Persian-alignment heuristic
should not be applied to fixed multiword expressions.
"""

from __future__ import annotations

from multiword_cards_phrasal_verbs import card


def idiom(word, cefr, fa, en, ex, ex_fa, syn, ant, coll, topic, skill, band,
          mistake=""):
    return card(word, cefr, fa, en, ex, ex_fa, syn, ant, coll, topic, skill,
                band, mistake=mistake, pos="idiom")


DISCOURSE = [
    idiom("there is growing evidence that", "C1",
          "شواهد روزافزونی وجود دارد که",
          "Used to introduce a claim that research increasingly supports.",
          "There is growing evidence that flexible hours raise productivity.",
          "شواهد روزافزونی وجود دارد که ساعت کاری انعطاف‌پذیر بهره‌وری را افزایش می‌دهد.",
          ["research increasingly shows that", "there is clear evidence that"],
          ["there is no evidence that"],
          ["there is growing evidence that X", "there is growing evidence to suggest that"],
          ["Research", "Health", "Science"], ["Reading Academic", "Writing"], "8.0",
          mistake="Follow it with a full clause, not a noun phrase: not 'there is growing evidence that the effects'."),
    idiom("a growing body of evidence suggests", "C1",
          "بدنهٔ روزافزونی از شواهد نشان می‌دهد",
          "Used to say that many separate studies point the same way.",
          "A growing body of evidence suggests that early intervention works best.",
          "بدنهٔ روزافزونی از شواهد نشان می‌دهد که مداخلهٔ زودهنگام بهترین نتیجه را دارد.",
          ["there is growing evidence that", "accumulating evidence indicates"],
          ["a handful of studies suggests"],
          ["a growing body of evidence suggests that", "which a growing body of evidence suggests"],
          ["Research", "Health", "Science"], ["Reading Academic", "Writing"], "8.0"),
    idiom("it is widely believed that", "B2",
          "به‌طور گسترده believed است که؛ باور عامه این است که",
          "Used to report a common assumption without endorsing it fully.",
          "It is widely believed that talent can be developed through practice.",
          "به‌طور گسترده believed است که استعداد از طریق تمرین قابل پرورش است.",
          ["it is generally accepted that", "many people believe that"], ["no one believes that"],
          ["it is widely believed that X", "as is widely believed"],
          ["Society", "Education", "Science"], ["Writing", "Reading Academic"], "7.0",
          mistake="This hedges the claim; do not use it when you can cite a specific study."),
    idiom("it could be argued that", "C1",
          "می‌توان استدلال کرد که",
          "Used to present an interpretation that readers could dispute.",
          "It could be argued that the policy penalises rural schools.",
          "می‌توان استدلال کرد که این سیاست مدارس روستایی را جریمه می‌کند.",
          ["one could argue that", "it is arguable that"], ["it is certain that"],
          ["it could be argued that X", "some might argue that"],
          ["Society", "Education", "Economics"], ["Writing", "Speaking"], "8.0"),
    idiom("plays a crucial role in", "B2",
          "نقشی حیاتی در ... دارد",
          "Used to say that something is essential to a result.",
          "Early diagnosis plays a crucial role in surviving the illness.",
          "تشخیص زودهنگام نقشی حیاتی در بقای بیماری دارد.",
          ["is central to", "is vital to", "is essential to"], ["is irrelevant to"],
          ["plays a crucial role in X", "which plays a crucial role in"],
          ["Health", "Education", "Society"], ["Reading Academic", "Writing"], "7.0"),
    idiom("has a significant impact on", "B2",
          "تأثیر چشمگیری بر ... دارد",
          "Used to say that something strongly affects an outcome.",
          "Screen time has a significant impact on children's sleep.",
          "زمان صفحه‌نمایش تأثیر چشمگیری بر خواب کودکان دارد.",
          ["strongly affects", "has a marked effect on"], ["has no bearing on"],
          ["has a significant impact on X", "which has a significant impact on"],
          ["Health", "Technology", "Education"], ["Reading Academic", "Writing"], "7.0"),
    idiom("the extent to which", "C1",
          "میزانی که؛ حدی که",
          "Used to introduce how far something is true.",
          "The extent to which the drug helps depends on the dose.",
          "میزان اثربخشی دارو به دوز آن بستگی دارد.",
          ["how far", "the degree to which"], ["the fact that"],
          ["to the extent to which X", "the extent to which this is true"],
          ["Research", "Science"], ["Reading Academic", "Writing"], "7.5"),
    idiom("a double-edged sword", "C1",
          "شمشیر دولبه؛ چیزی که هم سود هم زیان دارد",
          "An advantage that also creates a new problem.",
          "Automation is a double-edged sword for the manufacturing sector.",
          "اتوماسیون برای بخش تولید شمشیر دولبه است.",
          ["a mixed blessing", "a blessing and a curse"], ["a clear benefit"],
          ["prove to be a double-edged sword", "is something of a double-edged sword"],
          ["Technology", "Work", "Economics"], ["Speaking", "Writing"], "7.5"),
    idiom("the tip of the iceberg", "C1",
          "نوک کوه یخ؛ بخش کوچکی از یک مشکل بزرگ",
          "The small part of a difficulty that is visible.",
          "The reported cases are only the tip of the iceberg.",
          "موارد گزارش‌شده تنها نوک کوه یخ است.",
          ["only part of the problem", "the visible part of a larger problem"], ["the whole story"],
          ["is only the tip of the iceberg", "just the tip of the iceberg"],
          ["Health", "Crime", "Environment"], ["Speaking", "Writing"], "7.5"),
    idiom("a blunt instrument", "C1",
          "ابزار کند؛ وسیله‌ای ناکارآمد",
          "A measure that is too crude to achieve a precise result.",
          "A blunt instrument such as a total ban rarely improves compliance.",
          "ابزاری کند مانند ممنوعیت کامل، به‌ندرت پایبندی را بهبود می‌دهد.",
          ["an ineffective tool", "a crude measure"], ["a precise instrument"],
          ["regarded as a blunt instrument", "a blunt instrument for tackling"],
          ["Crime", "Government"], ["Writing", "Reading Academic"], "8.0"),
    idiom("the root cause", "C1",
          "علت ریشه‌ای؛ ریشهٔ مشکل",
          "The underlying reason a problem exists.",
          "Investigators are looking for the root cause of the contamination.",
          "محققان در جست‌وجوی علت ریشه‌ای آلودگی هستند.",
          ["the underlying cause", "the fundamental cause"], ["the symptoms"],
          ["identify the root cause of", "address the root cause"],
          ["Health", "Crime", "Science"], ["Reading Academic", "Writing"], "7.5"),
    idiom("a vicious circle", "C1",
          "دایرهٔ شیطانی؛ چرخهٔ معیوب",
          "A situation in which a problem causes itself to continue.",
          "Low wages and poor housing form a vicious circle.",
          "دستمزد پایین و مسکن نامناسب دایره‌ای شیطانی می‌سازند.",
          ["a vicious cycle", "a self-reinforcing cycle"], ["a virtuous circle"],
          ["creates a vicious circle", "trap families in a vicious circle"],
          ["Society", "Economics", "Health"], ["Speaking", "Writing"], "7.5"),
    idiom("a drop in the ocean", "B2",
          "قطره‌ای در دریا؛ ناچیز در برابر عظمت مسئله",
          "Something too small to make a real difference.",
          "The private donation was a drop in the ocean compared with the damage.",
          "کمک بخش خصوصی در مقایسه با خسارت وارده قطره‌ای در دریا بود.",
          ["a negligible contribution", "insignificant in comparison"], ["a decisive contribution"],
          ["a drop in the ocean compared with", "prove to be a drop in the ocean"],
          ["Society", "Environment"], ["Speaking", "Writing"], "7.0"),
    idiom("far from", "B1",
          "دور از؛ به‌هیچ‌وجه",
          "Used to emphasise that the opposite of a statement is true.",
          "The problem is far from being solved.",
          "این مسئله به‌هیچ‌وجه حل نشده است.",
          ["nowhere near", "anything but"], ["very nearly"],
          ["far from being", "far from enough", "far from true"],
          ["Society", "Science"], ["Writing", "Speaking"], "6.5"),
    idiom("in a broad sense", "C1",
          "در معنای کلی؛ به‌طور کلی",
          "In a general rather than a precise sense.",
          "Both languages are related in a broad sense.",
          "دو زبان به‌طور کلی با هم مرتبط‌اند.",
          ["in a general way", "broadly speaking"], ["strictly speaking"],
          ["true in a broad sense", "in a broad sense it is"],
          ["Science", "Education"], ["Reading Academic", "Writing"], "7.5"),
    idiom("put it another way", "C1",
          "به بیانی دیگر؛ طور دیگر بگویم",
          "Used to restate a point more simply.",
          "Put it another way, the two systems are not compatible.",
          "به بیانی دیگر، دو سامانه با هم سازگار نیستند.",
          ["in other words", "to put it differently"], [],
          ["to put it another way", "put another way"],
          ["Society", "Science"], ["Speaking", "Writing"], "7.5"),
    idiom("play down", "C1",
          "کم‌رنگ کردن؛ ناچیز جلوه دادن",
          "To make something seem less serious than it is.",
          "The minister played down the risks of the new programme.",
          "وزیر ریسک‌های برنامهٔ جدید را کم‌رنگ جلوه داد.",
          ["downplay", "minimise", "gloss over"], ["play up"],
          ["play down the risks", "play down the importance of"],
          ["Government", "Media"], ["Reading Academic", "Writing"], "7.5"),
    idiom("play up", "C1",
          "بزرگ نمایی کردن؛ تأکید کردن بر",
          "To make something seem more important than it is.",
          "The advertisement plays up the convenience of online banking.",
          "آگهی تبلیغاتی بر راحتی بانکداری آنلاین تأکید می‌کند.",
          ["emphasise", "highlight", "stress"], ["play down"],
          ["play up the benefits of", "play up the importance of"],
          ["Media", "Advertising"], ["Reading Academic", "Writing"], "7.5"),
    idiom("draw a line under", "C1",
          "خط پایان کشیدن بر؛ پرونده را بستن",
          "To end a discussion or a phase definitively.",
          "The court drew a line under the dispute by refusing further appeals.",
          "دادگاه با رد تجدیدنظرهای بیشتر خط پایانی بر اختلاف کشید.",
          ["put an end to", "conclude"], ["reopen"],
          ["draw a line under X", "finally draw a line under"],
          ["Crime", "Society"], ["Reading Academic", "Writing"], "8.0"),
    idiom("come to the fore", "C1",
          "برجسته شدن؛ به کانون توجه آمدن",
          "To become important or noticed after a period in the background.",
          "Mental health has come to the fore since the pandemic.",
          "از زمان همه‌گیری، سلامت روان به کانون توجه آمده است.",
          ["become prominent", "gain prominence"], ["fade into the background"],
          ["come to the fore in", "has recently come to the fore"],
          ["Health", "Society", "Government"], ["Reading Academic", "Writing"], "7.5"),
    idiom("rule of thumb", "C1",
          "قاعدهٔ سرانگشتی؛ قاعدهٔ کلی تجربی",
          "A simple practical guideline rather than a strict rule.",
          "As a rule of thumb, allow six months of preparation per band.",
          "به‌عنوان قاعده‌ای سرانگشتی، برای هر نمره شش ماه زمان آمادگی در نظر بگیرید.",
          ["general guideline", "rough guide"], ["strict rule"],
          ["as a rule of thumb", "a useful rule of thumb"],
          ["Education", "Work"], ["Speaking", "Writing"], "7.5"),
    idiom("beyond the scope of", "C1",
          "خارج از محدودهٔ؛ فراتر از دامنهٔ",
          "Too wide or too difficult for a particular discussion or study.",
          "Comparing the two systems in detail is beyond the scope of this paper.",
          "مقایسهٔ دقیق دو سامانه خارج از دامنهٔ این مقاله است.",
          ["outside the limits of", "too broad for"], ["within the scope of"],
          ["beyond the scope of this study", "largely beyond the scope of"],
          ["Research", "Science"], ["Reading Academic", "Writing"], "8.0"),
    idiom("in essence", "C1",
          "در جوهرِ؛ در اصل",
          "Used to summarise the most important point.",
          "In essence, the two proposals differ only in how they are funded.",
          "در جوهر، دو پیشنهاد تنها در نحوهٔ تأمین مالی تفاوت دارند.",
          ["essentially", "in substance", "basically"], ["in detail"],
          ["in essence, however", "in essence the same"],
          ["Science", "Society"], ["Writing", "Speaking"], "7.5"),
    idiom("a matter of course", "C1",
          "امری طبیعی؛ کاری که بدیهی است",
          "Something done as a normal part of a routine.",
          "Weekly safety checks are simply a matter of course here.",
          "بازرسی‌های ایمنی هفتگی در اینجا امری کاملاً طبیعی است.",
          ["standard practice", "routine"], ["a matter of concern"],
          ["as a matter of course", "is a matter of course"],
          ["Work", "Health"], ["Reading Academic", "Writing"], "7.5"),
    idiom("a matter of concern", "C1",
          "موضوع نگرانی؛ مسئلهٔ قابل توجه",
          "Something that genuinely needs attention.",
          "The rise in waiting times is a matter of concern to the trust.",
          "افزایش زمان انتظار موضوعی نگران‌کننده برای نهاد است.",
          ["a worrying development", "a cause for concern"], ["a matter of course"],
          ["a matter of concern that", "which is a matter of concern"],
          ["Health", "Society"], ["Reading Academic", "Writing"], "7.5"),
    idiom("take on board", "C1",
          "در نظر گرفتن؛ جدی گرفتن",
          "To accept advice or an idea and act on it.",
          "The committee did not take on board the objections raised by residents.",
          "کمیته اعتراضات ساکنان را جدی نگرفت.",
          ["accept", "heed", "act on"], ["dismiss", "ignore"],
          ["fail to take on board", "should be taken on board"],
          ["Society", "Work", "Government"], ["Speaking", "Writing"], "7.5"),
    idiom("for the sake of", "B2",
          "به خاطرِ؛ جهتِ",
          "Used to explain the reason for doing something.",
          "Tests were delayed for the sake of public safety.",
          "آزمایش‌ها به دلیل ایمنی عمومی به تأخیر افتاد.",
          ["out of", "in order to ensure"], ["against"],
          ["for the sake of clarity", "for the sake of fairness"],
          ["Health", "Research"], ["Writing", "Speaking"], "6.5"),
    idiom("as it stands", "B2",
          "در وضعیت کنونی؛ آن‌گونه که هست",
          "Used to describe the present situation before any change.",
          "As it stands, the scheme is available in only four provinces.",
          "در وضعیت کنونی، این طرح تنها در چهار استان در دسترس است.",
          ["at present", "currently", "in its current state"], ["in the long run"],
          ["as it stands today", "as it stands, however"],
          ["Government", "Health", "Education"], ["Speaking", "Writing"], "7.0"),
    idiom("in the absence of evidence to the contrary", "C1",
          "در نبودِ شاهدی خلافِ",
          "Used to state that a reasonable view is held despite no proof either way.",
          "In the absence of evidence to the contrary, the simplest explanation is preferred.",
          "در نبود شاهدی خلاف آن، ساده‌ترین توضیح ترجیح داده می‌شود.",
          ["barring evidence otherwise", "unless proven otherwise"], ["conclusive proof that"],
          ["in the absence of evidence to the contrary, therefore"],
          ["Science", "Research"], ["Reading Academic", "Writing"], "8.0"),
    idiom("to a lesser extent", "C1",
          "تا حدی کمتر؛ به میزان کمتری",
          "Used to say that something happens, but to a smaller degree.",
          "The same pattern appeared in rural schools, to a lesser extent.",
          "همین الگو در مدارس روستایی با میزان کمتری ظاهر شد.",
          ["to a certain degree", "to some extent"], ["to a great extent"],
          ["and, to a lesser extent, Y", "to a lesser extent in"],
          ["Science", "Society"], ["Reading Academic", "Writing"], "7.5"),
    idiom("in all likelihood", "C1",
          "به احتمال زیاد؛ به‌احتمال قوی",
          "Used to say that something is very probable.",
          "In all likelihood, the deadline will be extended again.",
          "به احتمال زیاد، مهلت بار دیگر تمدید خواهد شد.",
          ["almost certainly", "very probably"], ["improbably", "against all likelihood"],
          ["in all likelihood it will", "which in all likelihood"],
          ["Economics", "Government", "Science"], ["Writing", "Speaking"], "7.5"),
    idiom("a hard truth", "C1",
          "حقیقت تلخ؛ واقعیت دشوار",
          "An unwelcome fact that people tend to avoid.",
          "There is a hard truth about this sector: the current model cannot be sustained.",
          "در این بخش حقیقتی تلخ وجود دارد: مدل کنونی پایدار نیست.",
          ["an unwelcome reality", "a blunt fact"], ["a pleasant illusion"],
          ["face a hard truth", "a hard truth about"],
          ["Economics", "Environment", "Society"], ["Speaking", "Writing"], "7.5"),
    idiom("at stake", "C1",
          "در خطرِ؛ در میانِ گروگان",
          "At risk of being lost or damaged.",
          "Thousands of livelihoods are at stake in this decision.",
          "هزاران شغل در این تصمیم در معرض خطرند.",
          ["in danger", "at risk"], ["out of danger"],
          ["what is at stake", "much is at stake"],
          ["Economics", "Health", "Society"], ["Speaking", "Writing"], "7.5"),
    idiom("in the same vein", "C1",
          "به همین ترتیب؛ به همان شیوه",
          "Used to show that a new point is of the same kind as an earlier one.",
          "In the same vein, the neighbouring district reported similar figures.",
          "به همین ترتیب، منطقهٔ همسایه نیز ارقام مشابهی گزارش کرد.",
          ["likewise", "similarly", "in a similar way"], ["by contrast"],
          ["in the same vein, however", "and, in the same vein"],
          ["Society", "Research"], ["Speaking", "Writing"], "7.5"),
    idiom("a case in point", "C1",
          "نمونهٔ بارز؛ شاهد عینی",
          "A clear example that proves the point being made.",
          "The abandoned mill is a case in point for long-term industrial decline.",
          "کارخانهٔ متروکه نمونهٔ بارزی برای زوال بلندمدت صنعت است.",
          ["a clear example", "a telling example"], ["an exception"],
          ["a case in point is X", "is a case in point"],
          ["Society", "Urbanisation", "Economics"], ["Writing", "Speaking"], "7.5"),
    idiom("a double benefit", "B2",
          "فایدهٔ دوگانه؛ سود مضاعف",
          "An advantage that produces two positive results.",
          "Walking to school is a double benefit for health and emissions.",
          "پیاده رفتن به مدرسه هم برای سلامت و هم برای انتشار گازها فایدهٔ دوگانه دارد.",
          ["a twofold advantage", "mutual benefit"], ["a single drawback"],
          ["offers a double benefit", "a double benefit for"],
          ["Health", "Environment"], ["Speaking", "Writing"], "7.0"),
    idiom("at face value", "C1",
          "به‌ظاهر؛ در نگاه نخست",
          "In the way something appears, without examining it further.",
          "Taken at face value, the figures suggest steady growth.",
          "در نگاه نخست، ارقام رشدی پیوسته را نشان می‌دهند.",
          ["at first glance", "on the surface"], ["in reality"],
          ["take something at face value", "taken at face value"],
          ["Research", "Economics"], ["Reading Academic", "Writing"], "7.5"),
    idiom("a means of", "B2",
          "وسیله‌ای برای؛ راهی برای",
          "A method by which something is achieved.",
          "Language classes are a means of improving integration.",
          "کلاس‌های زبان وسیله‌ای برای بهبود ادغام هستند.",
          ["a way of", "a method of"], ["an obstacle to"],
          ["serve as a means of", "an effective means of"],
          ["Education", "Society"], ["Writing", "Reading Academic"], "7.0"),
    idiom("give way to", "C1",
          "تسلیم شدن به؛ جا دادن به",
          "To be replaced by something else, or to stop resisting.",
          "Over several decades, coal gave way to natural gas.",
          "طی چند دهه، زغال‌سنگ جای خود را به گاز طبیعی داد.",
          ["make way for", "be replaced by", "succumb to"], ["resist"],
          ["give way to pressure", "gradually give way to"],
          ["Environment", "Technology", "Society"], ["Reading Academic", "Writing"], "7.5"),
    idiom("a matter of life and death", "B1",
          "امری حیاتی؛ مسئله‌ای سرنوشت‌ساز",
          "Something extremely serious, with urgent consequences.",
          "For those patients, access to the drug is a matter of life and death.",
          "برای آن بیماران، دسترسی به دارو امری حیاتی است.",
          ["critically important", "a matter of survival"], ["a trivial matter"],
          ["treat something as a matter of life and death"],
          ["Health", "Crime"], ["Speaking", "Writing"], "6.5"),
    idiom("against all odds", "C1",
          "علی‌رغم همهٔ احتمالات؛ با وجود معارض‌ها",
          "In spite of strong reasons to expect failure.",
          "Against all odds, the team completed the survey on time.",
          "علی‌رغم همهٔ احتمالات، تیم نظرسنجی را به‌موقع به پایان رساند.",
          ["in spite of everything", "despite the odds"], ["as expected"],
          ["against all odds it worked", "completed against all odds"],
          ["Society", "Health", "Science"], ["Speaking", "Writing"], "7.5"),
    idiom("in the same boat", "B1",
          "در یک کشتی؛ در موقعیت مشابه",
          "In the same difficult situation as someone else.",
          "Small landlords found themselves in the same boat as their tenants.",
          "مالکان کوچک خود را در موقعیت مشابه مستأجرانشان یافتند.",
          ["in a similar predicament", "facing the same problem"], ["better off"],
          ["find yourself in the same boat", "we are all in the same boat"],
          ["Economics", "Society"], ["Speaking", "Writing"], "6.5"),
    idiom("on the surface", "B2",
          "در ظاهر؛ روی سطح",
          "Appearing to be the case when you look only at the obvious facts.",
          "On the surface the plan looks expensive, but the returns are high.",
          "در ظاهر طرح گران به نظر می‌رسد، اما بازده آن بالاست.",
          ["at first glance", "apparently"], ["in reality"],
          ["on the surface at least", "looks good on the surface"],
          ["Economics", "Science"], ["Speaking", "Writing"], "7.0"),
    idiom("bear in mind", "B1",
          "در نظر داشتن؛ به خاطر سپردن",
          "To remember something important when making a decision.",
          "Researchers should bear in mind that participants behave differently when observed.",
          "پژوهشگران باید در نظر داشته باشند که شرکت‌کنندگان هنگام مشاهده رفتار متفاوتی دارند.",
          ["keep in mind", "remember", "take into account"], ["forget"],
          ["bear in mind that", "it should be borne in mind that"],
          ["Research", "Education"], ["Writing", "Speaking"], "6.5"),
    idiom("come down to", "B2",
          "بستگی داشتن به؛ در نهایت به ... رسیدن",
          "To have its essential point or result in something.",
          "The debate ultimately comes down to how the money should be raised.",
          "مناقشه در نهایت به این بازمی‌گردد که پول چگونه باید تأمین شود.",
          ["amount to", "reduce to"], ["differ from"],
          ["it all comes down to", "ultimately comes down to"],
          ["Economics", "Society", "Politics"], ["Speaking", "Writing"], "7.0"),
    idiom("a fair amount of", "B2",
          "مقدار قابل توجهی از؛ حجم نسبتاً زیادی",
          "A quantity that is larger than expected.",
          "The repairs will require a fair amount of specialist equipment.",
          "تعمیرات به مقدار قابل توجهی تجهیزات تخصصی نیاز دارد.",
          ["a considerable amount of", "quite a lot of"], ["a negligible amount of"],
          ["a fair amount of work", "took a fair amount of"],
          ["Work", "Economics", "Health"], ["Speaking", "Writing"], "7.0"),
    idiom("come at a cost", "B2",
          "با هزینه همراه بودن؛ هزینه‌ای داشتن",
          "To involve an unpleasant or undesirable sacrifice.",
          "Rapid growth came at a cost to the rural population.",
          "رشد سریع به قیمت جمعیت روستایی تمام شد.",
          ["come at a price", "have a cost"], ["come free"],
          ["come at a cost to", "everything comes at a cost"],
          ["Economics", "Society", "Health"], ["Writing", "Speaking"], "7.0"),
    idiom("by no means", "C1",
          "به‌هیچ‌وجه؛ ابداً",
          "Used to emphasise that something is definitely not true.",
          "The scheme is by no means perfect, but it is a genuine improvement.",
          "این طرح به‌هیچ‌وجه بی‌عیب نیست، اما بهبودی واقعی است.",
          ["in no way", "not at all", "definitely not"], ["certainly"],
          ["by no means perfect", "by no means the only"],
          ["Society", "Science"], ["Writing", "Speaking"], "7.5"),
    idiom("a close call", "B2",
          "فرار از خطر در آخرین لحظه؛ موارد نزدیک",
          "A situation in which danger or failure was only narrowly avoided.",
          "The flight was a close call after the engine caught fire.",
          "پرواز پس از آتش‌سگرفتن موتور، فراری نزدیک از خطر بود.",
          ["a narrow escape", "a lucky escape"], ["a comfortable outcome"],
          ["a close call with disaster", "was a close call"],
          ["Transport", "Health"], ["Speaking", "Writing"], "7.0"),
    idiom("open the door to", "C1",
          "گشودن راه برای؛ امکان‌پذیر کردن",
          "To make a new possibility available.",
          "Cheap credit opened the door to home ownership for many families.",
          "وام ارزان راه خانه‌دار شدن را برای بسیاری از خانواده‌ها گشود.",
          ["create the possibility of", "pave the way for"], ["close the door on"],
          ["open the door to new", "opens the door to further"],
          ["Economics", "Technology", "Society"], ["Writing", "Reading Academic"], "7.5"),
    idiom("carry weight", "C1",
          "تأثیر گذاشتن؛ اعتبار داشتن",
          "To have influence or importance in a decision.",
          "The recommendation carried little weight with the ministry.",
          "این توصیه‌نامه برای وزارتخانه وزن چندانی نداشت.",
          ["have influence", "carry authority"], ["count for nothing"],
          ["carry weight with", "carry considerable weight"],
          ["Government", "Work"], ["Reading Academic", "Writing"], "8.0"),
    idiom("out of reach", "B2",
          "خارج از دسترس؛ دور از دسترس",
          "Too far away or too expensive to obtain.",
          "Good childcare is out of reach for most single parents.",
          "مراقبت مناسب از کودک برای بیشتر والدین تک‌والد خارج از دسترس است.",
          ["unattainable", "beyond reach"], ["within reach"],
          ["remain out of reach", "out of reach for most"],
          ["Society", "Economics", "Family"], ["Speaking", "Writing"], "6.5"),
    idiom("in the driver’s seat", "B1",
          "در موقعیت کنترل؛ عهده‌دار تصمیم",
          "In a position of control or authority.",
          "The new director is firmly in the driver's seat.",
          "مدیر جدید به‌طور محکم عهده‌دار تصمیم‌گیری است.",
          ["in control", "calling the shots"], ["powerless"],
          ["be in the driver's seat", "put someone in the driver's seat"],
          ["Work", "Politics"], ["Speaking", "Writing"], "7.0"),
    idiom("no stone unturned", "C1",
          "هیچ کاری را ناتوان گذاشتن؛ همهٔ تلاش‌ها را کردن",
          "Used to say that every possible effort was made.",
          "The auditors left no stone unturned in tracing the missing funds.",
          "حسابرسان برای ردیابی وجوه گمشده هیچ کاری را ناتوان گذاشت.",
          ["spare no effort", "do everything possible"], ["give up early"],
          ["leave no stone unturned in", "left no stone unturned"],
          ["Crime", "Research"], ["Reading Academic", "Writing"], "8.0"),
    idiom("a last resort", "B2",
          "آخرین راه‌حل؛ آخرین انتخاب",
          "An option used only when nothing else works.",
          "A diet of takeaway food is a last resort, not a routine.",
          "غذای آماده آخرین راه‌حل است، نه یک کار معمول.",
          ["a final option", "the final step"], ["the first choice"],
          ["as a last resort", "only as a last resort"],
          ["Health", "Family"], ["Speaking", "Writing"], "7.0"),
    idiom("in the public eye", "C1",
          "تحت نظر افکار عمومی؛ جلوی چشم مردم",
          "Receiving a great deal of attention from the public.",
          "After the scandal the director was no longer really in the public eye.",
          "پس از رسوایی، دیگر مدیر واقعاً در معرض دید افکار عمومی نبود.",
          ["in the public spotlight", "under public scrutiny"], ["out of the public eye"],
          ["in the public eye for", "remain in the public eye"],
          ["Media", "Politics", "Society"], ["Reading Academic", "Writing"], "7.5"),
    idiom("a double standard", "C1",
          "استاندارد دوگانه؛ معیار ناعادلانه",
          "Treating similar situations in different, unfair ways.",
          "Applying a double standard to two states is widely condemned.",
          "اعمال استاندارد دوگانه بر دو کشور به‌طور گسترده محکوم می‌شود.",
          ["an unfair comparison", "inconsistent treatment"], ["fair dealing"],
          ["apply a double standard to", "what appears to be a double standard"],
          ["Politics", "Society", "Crime"], ["Reading Academic", "Writing"], "8.0"),
    idiom("in no position to", "C1",
          "در موقعیتی نبودن که؛ ناتوان از",
          "Not able to do something because of circumstances or lack of right.",
          "Without funding the team was in no position to continue the trial.",
          "بدون بودجه، تیم در موقعیتی نبود که بتواند آزمایش را ادامه دهد.",
          ["unable to", "not in a position to"], ["well placed to"],
          ["in no position to help", "in no position to comment"],
          ["Work", "Research", "Health"],           ["Speaking", "Writing"], "7.5"),
]
