#!/usr/bin/env python3
"""Curated academic phrasal verbs for IELTS and TOEFL.

Every card is original editorial content. See curated_multiword_catalog.py for
the authoring rules each card must satisfy.
"""

from __future__ import annotations


def card(word, cefr, fa, en, ex, ex_fa, syn, ant, coll, topic, skill, band,
         mistake="", fam=None, pos="phrasal verb"):
    return {
        "word": word, "pos": pos, "cefr": cefr, "fa": fa, "en": en,
        "ex": ex, "exFa": ex_fa, "syn": syn, "ant": ant, "coll": coll,
        "fam": fam or [], "mistake": mistake, "topic": topic,
        "skill": skill, "band": band,
    }


PHRASAL_VERBS = [
    card("account for", "B2",
         "تشکیل دادن؛ سهم داشتن در؛ توضیح دادن",
         "To form a part of a total, or to explain why something happens.",
         "Renewable sources now account for nearly half of the country's electricity supply.",
         "منابع تجدیدپذیر اکنون نزدیک به نیمی از برق کشور را تشکیل می‌دهند.",
         ["constitute", "make up", "represent"], ["be irrelevant to"],
         ["account for a large share", "account for half of", "to account for the difference"],
         ["Environment", "Energy", "Economics"], ["Reading Academic", "Speaking"], "7.0",
         fam=["accountable", "accountability"]),
    card("add up to", "B2",
         "مجموع شدن؛ در مجموع برابر بودن با",
         "To reach a total when separate amounts are combined.",
         "The three separate estimates add up to a figure that is far too optimistic.",
         "سه تخمین جداگانه در مجموع به رقمی می‌رسند که بیش از حد خوش‌بینانه است.",
         ["amount to", "come to", "total"], ["fall short of"],
         ["add up to a total of", "the figures add up to"],
         ["Economics", "Research"], ["Reading Academic", "Writing"], "7.0",
         fam=["addition", "additional"]),
    card("allow for", "C1",
         "در نظر گرفتن؛ جایی برای در نظر گرفتن گذاشتن",
         "To consider something when making a plan or calculation.",
         "The forecast does not allow for the possibility of a sudden rise in demand.",
         "این پیش‌بینی احتمال افزایش ناگهانی تقاضا را در نظر نمی‌گیرد.",
         ["take into account", "make provision for", "consider"], ["ignore"],
         ["allowing for delays", "to allow for inflation", "allow for change"],
         ["Research", "Economics"], ["Reading Academic", "Writing"], "7.5"),
    card("appeal to", "C1",
         "جلب کردن علاقه؛ درخواست کردن از",
         "To attract someone's interest or support, or to make a formal request.",
         "Design alone rarely appeals to the audience; price and practicality matter more.",
         "طراحی به‌تنهایی به‌ندرت توجه مخاطب را جلب می‌کند؛ قیمت و کاربرد عملی مهم‌ترند.",
         ["attract", "resonate with"], ["alienate"],
         ["appeal to a broad audience", "appeal to common sense", "strongly appeal to"],
         ["Media", "Advertising", "Culture"], ["Listening Lecture", "Speaking"], "7.0"),
    card("attend to", "C1",
         "رسیدگی کردن به؛ توجه کردن به",
         "To deal with a problem, or to give something your attention.",
         "The clinic was slow to attend to complaints about waiting times.",
         "کلینیک در رسیدگی به شکایات مربوط به زمان انتظار کند بود.",
         ["deal with", "address", "handle"], ["ignore", "overlook"],
         ["attend to a matter", "fail to attend to", "attend to details"],
         ["Health", "Work", "Government"], ["Reading Academic", "Writing"], "7.0"),
    card("back up", "B1",
         "پشتیبانی کردن از؛ تأیید کردن؛ نسخهٔ پشتیبان گرفتن",
         "To support a claim with evidence, or to make a copy of data.",
         "The researcher backed up her claim with data from two large studies.",
         "پژوهشگر ادعای خود را با داده‌های دو مطالعهٔ بزرگ پشتیبانی کرد.",
         ["support", "substantiate", "confirm"], ["contradict", "refute"],
         ["back up a claim", "back up with evidence", "back up the argument"],
         ["Research", "Education"], ["Reading Academic", "Writing"], "6.5",
         mistake="Do not confuse the two-word verb 'back up' (to support) with the noun 'backup' (a copy).",
         fam=["backup", "backing"]),
    card("bring about", "C1",
         "به وجود آوردن؛ موجب شدن",
         "To cause something to happen as a result of an action or process.",
         "The new regulations were brought about by a series of safety incidents.",
         "مقررات جدید در نتیجهٔ چند حادثهٔ ایمنی پدید آمد.",
         ["cause", "trigger", "produce"], ["prevent"],
         ["bring about change", "bring about a decline", "help bring about"],
         ["Government", "Environment", "Health"], ["Reading Academic", "Writing"], "7.0"),
    card("bring up", "B1",
         "مطرح کردن؛ به موضوع آوردن؛ بزرگ کردن",
         "To raise a topic for discussion, or to raise a child.",
         "Several members brought up the issue of exam anxiety during the debate.",
         "چند عضو در طول بحث موضوع اضطراب امتحان را مطرح کردند.",
         ["raise", "mention"], ["suppress"],
         ["bring up an issue", "bring up a point", "bring up children"],
         ["Education", "Society"], ["Speaking", "Listening Conversation"], "6.5"),
    card("build on", "C1",
         "بر پایهٔ چیزی بنا نهادن؛ توسعه دادن",
         "To use an existing idea, result or achievement as a starting point.",
         "The course builds on the grammar students studied at secondary school.",
         "این دوره بر دستاوردهای گرامری دانش‌آموزان در دورهٔ متوسطه بنا شده است.",
         ["develop", "expand", "draw on"], ["discard"],
         ["build on existing research", "build on previous work", "build on success"],
         ["Education", "Research"], ["Reading Academic", "Writing"], "7.0"),
    card("brush up on", "C1",
         "مرور کردن؛ مروری بر چیزی انداختن",
         "To review something you have not practised for a while.",
         "She brushed up on her French before travelling to Lyon.",
         "او پیش از سفر به لیون مروری بر فرانسهٔ خود کرد.",
         ["review", "refresh", "revise"], ["neglect"],
         ["brush up on your skills", "brush up on a language"],
         ["Education", "Work"], ["Speaking", "Listening Conversation"], "7.0"),
    card("call for", "C1",
         "فراخوان دادن؛ خواستار بودن؛ ایجاب کردن",
         "To demand that something happen, or to need something urgently.",
         "The report calls for stricter limits on industrial emissions.",
         "این گزارش خواستار اعمال محدودیت‌های سخت‌گیرانه‌تر بر انتشار صنعتی است.",
         ["demand", "require", "urge"], ["dismiss"],
         ["call for reform", "calls for immediate action", "call for greater transparency"],
         ["Government", "Environment", "Work"], ["Reading Academic", "Writing"], "7.5"),
    card("carry on", "B1",
         "ادامه دادن؛ به کار خود ادامه دادن",
         "To continue doing what you were already doing.",
         "The museum will carry on repairing the roof until the autumn.",
         "موزه تا پاییز به تعمیر سقف ادامه خواهد داد.",
         ["continue", "proceed", "persist"], ["stop", "cease"],
         ["carry on working", "carry on despite", "carry on with the project"],
         ["Work", "Society"], ["Speaking", "Writing"], "6.0"),
    card("carry out", "B2",
         "انجام دادن؛ به اجرا درآوردن",
         "To perform a task, survey or experiment completely and carefully.",
         "The team carried out a survey of two thousand households across the region.",
         "این تیم نظرسنجی از دو هزار خانوار در سراسر منطقه انجام داد.",
         ["conduct", "perform", "execute"], ["abandon", "omit"],
         ["carry out research", "carry out a survey", "carry out an experiment"],
         ["Research", "Education", "Health"], ["Reading Academic", "Writing"], "7.0",
         mistake="Not the same as 'carry something out of a room', where 'out' shows direction."),
    card("cater for", "C1",
         "پاسخگو بودن به؛ برآورده کردن نیاز کسی",
         "To provide for a particular group or a range of needs.",
         "The new library caters for both young children and university students.",
         "کتابخانهٔ جدید هم برای کودکان خردسال و هم برای دانشجویان خدمات فراهم می‌کند.",
         ["serve", "provide for", "accommodate"], ["ignore"],
         ["cater for all needs", "cater for students", "designed to cater for"],
         ["Education", "Urbanisation", "Health"], ["Writing", "Speaking"], "7.0"),
    card("catch up with", "B2",
         "رسیدن به سطح دیگران؛ جبران عقب‌ماندگی",
         "To reach the same level as other people after falling behind.",
         "Adult learners worry that they will never catch up with their children.",
         "یادگیرندگان بزرگسال نگران‌اند که هرگز به سطح فرزندانشان نرسند.",
         ["overtake", "draw level with"], ["fall behind"],
         ["catch up with the rest", "struggle to catch up with"],
         ["Education", "Society"], ["Speaking", "Writing"], "6.5"),
    card("coincide with", "C1",
         "همزمان بودن با؛ مصادف بودن با",
         "To happen at the same time as something else.",
         "The festival coincides with the start of the rainy season.",
         "جشنواره با آغاز فصل باران مصادف است.",
         ["overlap with", "match"], ["precede", "follow"],
         ["coincide with the start", "happens to coincide with"],
         ["Culture", "Environment"], ["Reading Academic", "Writing"], "7.5"),
    card("come across", "C1",
         "برخورد کردن با؛ به نظر رسیدن",
         "To meet or find something by chance, or to seem a certain way.",
         "I came across an unusual phrase in an old textbook this morning.",
         "امروز صبح به یک عبارت غیرمعمول در یک کتاب قدیمی برخوردم.",
         ["encounter", "discover", "seem"], ["avoid"],
         ["come across as friendly", "come across a reference", "often comes across as"],
         ["Education", "Society"], ["Speaking", "Listening Conversation"], "7.0"),
    card("come to terms with", "C1",
         "کنار آمدن با؛ پذیرش واقعیت",
         "To accept an unpleasant situation as real.",
         "Many communities are still trying to come to terms with the closure of the factory.",
         "بسیاری از جوامع هنوز در تلاش برای پذیرش تعطیلی کارخانه هستند.",
         ["accept", "reconcile to", "adjust to"], ["deny", "resist"],
         ["come to terms with reality", "struggle to come to terms with"],
         ["Society", "Work", "Health"], ["Speaking", "Writing"], "7.5"),
    card("come up with", "B2",
         "به ذهن رسیدن؛ ابداع کردن",
         "To think of an idea, plan or solution.",
         "Students had to come up with their own design for the final project.",
         "دانشجویان باید طرح خود را برای پروژهٔ پایانی ابداع می‌کردند.",
         ["devise", "think of", "invent"], ["adopt"],
         ["come up with a solution", "come up with an idea", "manage to come up with"],
         ["Education", "Work", "Technology"], ["Speaking", "Writing"], "6.5"),
    card("comply with", "C1",
         "رعایت کردن؛ تبعیت کردن از",
         "To obey a rule, standard or official request.",
         "Most exporters complied with the new labelling rules before the deadline.",
         "بیشتر صادرکنندگان پیش از مهلت، مقررات جدید برچسب‌گذاری را رعایت کردند.",
         ["adhere to", "abide by", "conform to"], ["violate", "breach"],
         ["comply with regulations", "fully comply with", "fail to comply with"],
         ["Government", "Work", "Crime"], ["Reading Academic", "Writing"], "7.5",
         fam=["compliance", "compliant"]),
    card("confine to", "C1",
         "محدود کردن به؛ محصور بودن در",
         "To keep something within a limited area, group or time period.",
         "The damage was confined to the northern districts of the city.",
         "آسیب به مناطق شمالی شهر محدود شد.",
         ["limit", "restrict to", "keep within"], ["spread to"],
         ["confined to one region", "largely confined to", "confined to a small number of"],
         ["Health", "Environment", "Crime"], ["Reading Academic", "Writing"], "7.5"),
    card("contribute to", "B2",
         "کمک کردن به؛ نقش داشتن در؛ باعث شدن",
         "To give money or effort, or to be one reason for a result.",
         "Several factors contribute to the decline in reading among teenagers.",
         "عوامل متعددی در کاهش علاقهٔ نوجوانان به مطالعه نقش دارند.",
         ["add to", "play a part in", "lead to"], ["reduce", "hinder"],
         ["contribute to a decline", "contribute to the growth of", "significantly contribute to"],
         ["Education", "Health", "Environment"], ["Reading Academic", "Writing"], "7.0"),
    card("cope with", "B2",
         "کنار آمدن با؛ مقابله کردن با",
         "To deal successfully with a difficult situation.",
         "Small businesses have struggled to cope with the rise in energy prices.",
         "کسب‌وکارهای کوچک در مقابله با افزایش قیمت انرژی دشواری داشته‌اند.",
         ["deal with", "handle", "manage"], ["succumb to"],
         ["cope with pressure", "struggle to cope with", "cope effectively with"],
         ["Health", "Work", "Society"], ["Speaking", "Writing"], "7.0"),
    card("count on", "B2",
         "روی چیزی حساب کردن؛ به چیزی اطمینان داشتن",
         "To rely on something happening, or on someone's help.",
         "Early-career researchers should not count on a stable path to a permanent post.",
         "پژوهشگران تازه‌کار نباید روی مسیر پایداری برای رسیدن به جایگاه دائمی حساب کنند.",
         ["rely on", "depend on", "bank on"], ["doubt"],
         ["count on support", "can count on", "count on someone to"],
         ["Work", "Education"], ["Speaking", "Listening Conversation"], "7.0"),
    card("deal with", "B2",
         "رسیدگی کردن به؛ سر و کار داشتن با",
         "To handle a problem or situation, or to do business with someone.",
         "The course teaches students how to deal with conflict in the workplace.",
         "این دوره به دانشجویان می‌آموزد چگونه با تعارض در محیط کار برخورد کنند.",
         ["handle", "tackle", "address"], ["avoid", "shun"],
         ["deal with problems", "deal effectively with", "learn to deal with"],
         ["Work", "Education", "Crime"], ["Speaking", "Writing"], "6.5"),
    card("derive from", "C1",
         "نشئت گرفتن از؛ برگرفتن از",
         "To get something from a source, or to originate in something.",
         "Many of these benefits derive directly from improved sanitation.",
         "بسیاری از این مزایا به‌طور مستقیم از بهبود بهداشت نشئت می‌گیرند.",
         ["stem from", "originate from", "arise from"], ["ignore"],
         ["derive from a source", "derive pleasure from", "largely derives from"],
         ["Science", "Research", "Economics"], ["Reading Academic", "Writing"], "7.5"),
    card("differ from", "B1",
         "متفاوت بودن از؛ فرق داشتن با",
         "To be unlike something else in some way.",
         "The two languages differ from one another mainly in how they form plurals.",
         "این دو زبان عمدتاً در نحوهٔ ساخت جمع با یکدیگر تفاوت دارند.",
         ["vary from", "contrast with"], ["resemble", "match"],
         ["differ from one another", "differ significantly from", "differ in size"],
         ["Science", "Culture", "Education"], ["Reading Academic", "Writing"], "6.5"),
    card("dispose of", "C1",
         "دور انداختن؛ از بین بردن",
         "To throw something away or get rid of it.",
         "Hospitals must dispose of clinical waste safely and legally.",
         "بیمارستان‌ها باید پسماند بالینی را به‌طور ایمن و قانونی دور بریزند.",
         ["get rid of", "discard", "throw away"], ["keep", "retain"],
         ["dispose of waste", "safely dispose of", "properly disposed of"],
         ["Health", "Environment"], ["Reading Academic", "Writing"], "7.0"),
    card("draw up", "C1",
         "تدوین کردن؛ تنظیم کردن؛ ترسیم کردن",
         "To write a plan, list or contract, or to stop a moving vehicle.",
         "The committee drew up a set of guidelines for classroom use.",
         "کمیته مجموعه‌ای از دستورالعمل‌ها برای استفاده در کلاس تدوین کرد.",
         ["prepare", "compile", "draft"], ["discard"],
         ["draw up a plan", "draw up a list of", "draw up guidelines"],
         ["Work", "Crime", "Education"], ["Writing", "Reading Academic"], "7.5"),
    card("dwell on", "C1",
         "اصرار کردن بر؛ بیش از حد صحبت کردن از",
         "To think or talk about something for a long time.",
         "The report is careful not to dwell on the single year of decline.",
         "این گزارش مراقب است که بیش از حد روی تنها سال رکود تکرار نکند.",
         ["focus on", "linger on", "emphasise"], ["gloss over"],
         ["dwell on a point", "dwell too much on", "not dwell on"],
         ["Society", "Work"], ["Writing", "Speaking"], "7.5"),
    card("fall back on", "C1",
         "پناه بردن به؛ ناچار شدن به استفاده از",
         "To use something or someone when there is no other choice.",
         "When funding was cut, the laboratory fell back on equipment donations.",
         "هنگام کاهش بودجه، آزمایشگاه ناچار به استفاده از کمک‌های تجهیزاتی شد.",
         ["resort to", "turn to", "rely on"], ["refrain from"],
         ["fall back on reserves", "forced to fall back on", "fall back on defaults"],
         ["Economics", "Work", "Government"], ["Reading Academic", "Writing"], "7.5"),
    card("figure out", "B2",
         "درک کردن؛ فهمیدن؛ محاسبه کردن",
         "To understand something after thinking about it, or to calculate a value.",
         "It took me months to figure out why the two datasets disagreed.",
         "ماه‌ها طول کشید تا بفهمم چرا دو مجموعه‌داده با هم اختلاف داشتند.",
         ["work out", "understand", "establish"], ["ignore"],
         ["figure out the cause", "figure out how", "hard to figure out"],
         ["Science", "Research", "Education"], ["Speaking", "Listening Conversation"], "7.0"),
    card("focus on", "B1",
         "تمرکز کردن بر؛ توجه معطوف کردن به",
         "To give all your attention or effort to one thing.",
         "The campaign focuses on reducing household waste rather than on recycling it.",
         "این کمپینه بر کاهش پسماند خانگی به‌جای بازیافت آن تمرکز دارد.",
         ["concentrate on", "centre on"], ["neglect", "ignore"],
         ["focus on a problem", "focus primarily on", "refocus on"],
         ["Education", "Environment", "Health"], ["Speaking", "Writing"], "6.5"),
    card("get across", "C1",
         "منتقل کردن؛ رساندن پیام؛ فهمانده شدن",
         "To make an idea clear to someone, or to be understood.",
         "The message of the campaign did not get across to younger audiences.",
         "پیام کمپینه به مخاطبان جوان‌تر منتقل نشد.",
         ["convey", "communicate", "put across"], ["obscure"],
         ["get a message across", "get across to students", "hard to get across"],
         ["Media", "Education", "Advertising"], ["Speaking", "Listening Lecture"], "7.5"),
    card("get rid of", "B2",
         "خلاص شدن از؛ از بین بردن",
         "To remove, throw away or get free from something unwanted.",
         "The city is trying to get rid of waste without simply burying it.",
         "شهر تلاش می‌کند بدون دفن ساده، از پسماند خلاص شود.",
         ["eliminate", "remove", "dispose of"], ["retain"],
         ["get rid of waste", "get rid of a smell", "difficult to get rid of"],
         ["Environment", "Health", "Society"], ["Speaking", "Writing"], "6.5"),
    card("give in", "C1",
         "کوتاه آمدن؛ تسلیم شدن؛ فرو ریختن",
         "To stop resisting and accept what others want.",
         "After months of resistance, the committee finally gave in and approved the plans.",
         "پس از ماه‌ها مقاومت، کمیته سرانجام تسلیم شد و طرح‌ها را تصویب کرد.",
         ["yield", "surrender", "succumb"], ["resist", "hold out"],
         ["give in to pressure", "finally give in", "refuse to give in"],
         ["Society", "Work", "Government"], ["Speaking", "Listening Conversation"], "7.0"),
    card("give back", "B1",
         "بازگرداندن؛ بازگرداندن به جامعه",
         "To return something to someone, or to restore a situation.",
         "The scheme gives back part of every fee to local conservation work.",
         "این طرح بخشی از هر هزینه را به کارهای محلی حفاظت از محیط بازمی‌گرداند.",
         ["return", "restore"], ["withhold"],
         ["give back control", "give back to the community", "give something back"],
         ["Society", "Environment", "Culture"], ["Listening Lecture", "Speaking"], "6.0"),
    card("give in to", "C1",
         "تسلیم شدن در برابر؛ تسلیم",
         "To stop resisting something such as pressure or temptation.",
         "The hospital did not give in to demands for a shorter shift.",
         "بیمارستان تسلیم خواسته‌های مربوط به شیفت کوتاه‌تر نشد.",
         ["yield to", "succumb to", "surrender to"], ["resist"],
         ["give in to pressure", "refused to give in to"],
         ["Society", "Health", "Work"], ["Speaking", "Writing"], "7.5"),
    card("give rise to", "C1",
         "پدید آوردن؛ منجر شدن به",
         "To cause something to happen, especially something notable.",
         "Rapid urban growth has given rise to severe pressure on housing.",
         "رشد سریع شهری فشار شدیدی بر مسکن پدید آورده است.",
         ["lead to", "bring about", "result in"], ["put an end to"],
         ["give rise to concern", "give rise to new demand", "may give rise to"],
         ["Urbanisation", "Health", "Economics"], ["Writing", "Reading Academic"], "7.5"),
    card("go along with", "C1",
         "همراهی کردن با؛ پذیرفتن بی‌چون‌وچرا",
         "To agree with someone's opinion or decision without strong feeling.",
         "Few committee members were willing to go along with the proposal uncritically.",
         "اعضای کمی از کمیته حاضر نبودند بدون نقد پیشنهاد را بپذیرند.",
         ["agree with", "accept", "acquiesce"], ["oppose", "object to"],
         ["go along with a decision", "reluctant to go along with", "just go along with"],
         ["Society", "Government", "Work"], ["Listening Conversation", "Speaking"], "7.5"),
    card("hold back", "C1",
         "باز داشتن؛ مانع شدن؛ کنار گذاشتن",
         "To prevent something from happening, or to withhold something.",
         "Rising costs held back the recovery that officials had predicted.",
         "افزایش هزینه‌ها بازگشتی را که مقامات پیش‌بینی کرده بودند متوقف کرد.",
         ["restrain", "impede", "withhold"], ["release", "encourage"],
         ["hold back growth", "hold back information", "held back by"],
         ["Economics", "Work", "Government"], ["Reading Academic", "Writing"], "7.0"),
    card("hold on to", "C1",
         "حفظ کردن؛ نگه داشتن؛ چسبیدن به",
         "To keep something firmly, or to keep a value or a hope.",
         "Households should hold on to savings in case unemployment rises.",
         "خانوارها باید پس‌انداز خود را حفظ کنند تا در صورت افزایش بیکاری از آن استفاده کنند.",
         ["retain", "keep", "preserve"], ["release", "discard"],
         ["hold on to power", "hold on to control", "hold on to traditional values"],
         ["Economics", "Society", "Culture"], ["Listening Lecture", "Writing"], "7.5"),
    card("hold up", "C1",
         "به تأخیر انداختن؛ مانع شدن؛ دوام آوردن",
         "To delay something, or to continue working well.",
         "Severe weather held up deliveries for most of the week.",
         "هوای بد در بخش بزرگی از هفته تحویل‌ها را به تأخیر انداخت.",
         ["delay", "postpone", "impede"], ["expedite", "speed up"],
         ["hold up progress", "hold up well under pressure", "badly held up"],
         ["Transport", "Economics", "Work"], ["Speaking", "Writing"], "7.0"),
    card("keep up with", "B2",
         "همگام ماندن با؛ از قلم نیفتادن",
         "To stay at the same level as others who are progressing.",
         "Small firms find it hard to keep up with the pace of technical change.",
         "شرکت‌های کوچک به‌سختی می‌توانند با سرعت تغییرات فنی همگام بمانند.",
         ["stay abreast of", "keep pace with", "match"], ["fall behind"],
         ["keep up with demand", "difficult to keep up with", "keep up with the competition"],
         ["Technology", "Work", "Education"], ["Speaking", "Writing"], "6.5"),
    card("lay down", "C1",
         "بنیان نهادن؛ وضع کردن؛ تعیین کردن",
         "To establish a rule or principle.",
         "The charter lays down clear limits on what companies may store.",
         "این منشور حدود روشنی را برای آنچه شرکت‌ها مجاز به ذخیره‌سازی هستند تعیین می‌کند.",
         ["establish", "set down", "impose"], ["abolish"],
         ["lay down the law", "lay down strict rules", "laid down in the charter"],
         ["Crime", "Government", "Work"], ["Reading Academic", "Writing"], "7.5"),
    card("lay off", "B2",
         "اخراج کردن؛ بیکار کردن",
         "To dismiss workers because there is no work for them.",
         "When orders fell, the plant decided to lay off two hundred workers.",
         "وقتی سفارش‌ها کاهش یافت، کارخانه تصمیم گرفت دویست کارگر را اخراج کند.",
         ["dismiss", "make redundant"], ["hire", "recruit"],
         ["lay off staff", "laid off workers", "mass layoffs"],
         ["Work", "Economics"], ["Listening Lecture", "Writing"], "7.0"),
    card("lay out", "C1",
         "شرح دادن؛ بیان کردن؛ چیدمان کردن",
         "To explain something clearly, or to arrange objects in a pattern.",
         "The proposal lays out three stages of implementation over five years.",
         "این پیشنهاد سه مرحلهٔ اجرا را در طول پنج سال شرح می‌دهد.",
         ["set out", "explain", "present"], ["conceal"],
         ["lay out the plan", "lay out an argument", "clearly laid out"],
         ["Work", "Education", "Crime"], ["Writing", "Reading Academic"], "7.5"),
    card("live up to", "C1",
         "برآورده کردن؛ مطابقت داشتن با",
         "To match the reputation or promise that something has.",
         "The new stadium has not lived up to the promise of the campaign.",
         "ورزشگاه جدید به وعدهٔ کمپینی که داده بود پاسخ نداد.",
         ["match", "meet", "fulfil"], ["fall short of"],
         ["live up to expectations", "fail to live up to", "has lived up to its reputation"],
         ["Society", "Work", "Culture"], ["Speaking", "Writing"], "7.5"),
    card("look forward to", "B2",
         "مشتاقانه منتظر بودن؛ در انتظار بودن",
         "To feel pleased about something that will happen in the future.",
         "Applicants should look forward to a longer wait for a first interview.",
         "متقاضیان باید خود را برای انتظار طولانی‌تر نخستین مصاحبه آماده کنند.",
         ["anticipate", "await", "eager for"], ["dread"],
         ["look forward to hearing from you", "look forward to the future", "we look forward to"],
         ["Work", "Education"], ["Writing", "Speaking"], "6.5",
         mistake="'To' here is a preposition, so use a noun or a gerund, never an infinitive."),
    card("look into", "B2",
         "بررسی کردن؛ رسیدگی کردن به",
         "To investigate something carefully in order to understand it.",
         "The authority has agreed to look into complaints about noise levels.",
         "مقامات موافقت کرده‌اند شکایات مربوط به میزان سروصدا را بررسی کنند.",
         ["investigate", "examine", "probe"], ["ignore"],
         ["look into a matter", "look into the causes of", "promise to look into"],
         ["Crime", "Government", "Health"], ["Writing", "Listening Lecture"], "7.0"),
    card("make up", "B2",
         "تشکیل دادن؛ جبران کردن؛ آرایش کردن؛ دروغ گفتن",
         "To form something, to compensate for a loss, or to invent a story.",
         "Renewable sources make up a growing share of the country's energy mix.",
         "منابع تجدیدپذیر سهم روزافزونی از ترکیب انرژی کشور را تشکیل می‌دهند.",
         ["constitute", "compose", "compensate for"], ["dismantle"],
         ["make up a large proportion", "make up for the loss", "make up one's mind"],
         ["Economics", "Culture", "Society"], ["Writing", "Speaking"], "6.5",
         fam=["makeup", "upmade"]),
    card("narrow down", "C1",
         "محدود کردن؛ کاستن از دامنه",
         "To reduce a range of possibilities to a smaller number.",
         "Two experiments narrowed down the possible causes quite quickly.",
         "دو آزمایش به‌سرعت دامنهٔ علل ممکن را محدود کردند.",
         ["limit", "reduce", "focus"], ["broaden", "widen"],
         ["narrow down the search", "narrow down to a few", "narrowed down to"],
         ["Science", "Research", "Crime"], ["Reading Academic", "Writing"], "7.5"),
    card("pave the way for", "C1",
         "زمینه‌سازی کردن برای؛ راه را هموار کردن",
         "To make something possible or easier in the future.",
         "The pilot scheme paved the way for national reform.",
         "طرح آزمایشی راه را برای اصلاحات ملی هموار کرد.",
         ["prepare the way for", "enable", "facilitate"], ["hinder"],
         ["pave the way for reform", "paves the way for progress"],
         ["Government", "Technology", "Education"], ["Reading Academic", "Writing"], "7.5"),
    card("pay attention to", "B1",
         "توجه کردن به؛ دقت کردن بر",
         "To watch, listen or think carefully about something.",
         "Voters should pay attention to how campaign spending is reported.",
         "رای‌دهندگان باید به نحوهٔ گزارش هزینه‌های تبلیقاتی توجه کنند.",
         ["notice", "heed", "observe"], ["ignore"],
         ["pay close attention to", "pay attention to detail", "fail to pay attention to"],
         ["Education", "Media", "Government"], ["Reading Academic", "Writing"], "6.0"),
    card("pin down", "C1",
         "دقیقاً تعیین کردن؛ مشخص کردن",
         "To establish something exactly, such as a figure or a date.",
         "Auditors could not pin down the exact source of the discrepancy.",
         "حسابرسان نتوانستند منبع دقیق ناسازگاری را مشخص کنند.",
         ["determine", "establish", "identify"], ["vaguely suggest"],
         ["pin down a cause", "hard to pin down", "pin down the exact figure"],
         ["Research", "Crime", "Economics"], ["Reading Academic", "Writing"], "7.5"),
    card("point out", "B2",
         "اشاره کردن به؛ نشان دادن",
         "To mention something that others may not have noticed.",
         "The auditor pointed out several inconsistencies in the accounts.",
         "حسابرس چند ناسازگاری در حساب‌ها را نشان داد.",
         ["highlight", "note", "indicate"], ["overlook"],
         ["point out that", "point out the problem", "worth pointing out that"],
         ["Research", "Economics", "Crime"], ["Writing", "Reading Academic"], "7.0"),
    card("put forward", "C1",
         "مطرح کردن؛ ارائه دادن؛ پیشنهاد کردن",
         "To suggest an idea or plan for other people to consider.",
         "Several researchers put forward similar explanations in the same year.",
         "چند پژوهشگر در همان سال توضیح‌های مشابهی مطرح کردند.",
         ["propose", "advance", "suggest"], ["withdraw"],
         ["put forward a proposal", "put forward a theory", "put forward arguments for"],
         ["Research", "Work", "Crime"], ["Writing", "Reading Academic"], "7.5"),
    card("put off", "B2",
         "به تعویق انداختن؛ طفره رفتن از",
         "To delay something, or to discourage someone.",
         "Bad weather forced organisers to put off the final for a fortnight.",
         "هوای بد ناگزیر کرد برگزارکنندگان فینال را دو هفته به تعویق بیندازند.",
         ["postpone", "delay", "defer"], ["expedite"],
         ["put off a decision", "put off until", "keep putting off"],
         ["Work", "Education", "Culture"], ["Speaking", "Writing"], "7.0"),
    card("put up with", "B2",
         "تحمل کردن؛ کنار آمدن با",
         "To accept a bad or unpleasant situation without complaining.",
         "Staff had to put up with a crumbling building for years before anyone acted.",
         "کارکنان سال‌ها ناچار بودند ساختمانی فروریخته را تحمل کنند تا کسی اقدامی نکند.",
         ["tolerate", "endure", "stand"], ["resist", "refuse"],
         ["put up with pressure", "hard to put up with", "no longer willing to put up with"],
         ["Work", "Health", "Society"], ["Speaking", "Writing"], "6.5",
         mistake="Always three words: 'put up with', never 'putup with' or 'put with'."),
    card("refer to", "B2",
         "اشاره کردن به؛ ارجاع دادن به؛ مراجعه کردن به",
         "To mention something, or to look at a source for information.",
         "The term refers to a practice recorded in early printing shops and never formally defined.",
         "این اصطلاح به شیوه‌ای اشاره دارد که در کارگاه‌های چاپ نخستین ثبت شد و هرگز به‌طور رسمی تعریف نشد.",
         ["allude to", "mention", "cite"], ["omit"],
         ["refer to a figure", "refer back to", "refer to the appendix"],
         ["Research", "Science", "Education"], ["Reading Academic", "Writing"], "7.0"),
    card("result in", "B2",
         "منجر شدن به؛ در نتیجه داشتن",
         "To cause a particular outcome.",
         "Prolonged drought resulted in the failure of two harvests.",
         "خشکسالی طولانی به شکست دو محصول کشاورزی انجامید.",
         ["lead to", "cause", "bring about"], ["prevent"],
         ["result in a decline", "result in serious harm", "directly results in"],
         ["Environment", "Health", "Economics"], ["Reading Academic", "Writing"], "7.0"),
    card("rule out", "C1",
         "منتفی کردن؛ رد کردن؛ کنار گذاشتن",
         "To eliminate a possibility, or to prevent something from being allowed.",
         "Researchers have not ruled out contamination of the water supply.",
         "پژوهشگران آلودگی منابع آب را منتفی اعلام نکرده‌اند.",
         ["exclude", "eliminate", "preclude"], ["permit", "allow for"],
         ["rule out the possibility of", "cannot be ruled out", "rule out a theory"],
         ["Science", "Health", "Crime"], ["Reading Academic", "Writing"], "7.5"),
    card("set about", "C1",
         "شروع کردن به؛ دست به کار شدن",
         "To begin doing something that takes effort.",
         "The council set about reviewing the whole planning system.",
         "شورا کار بازبینی کل نظام برنامه‌ریزی را آغاز کرد.",
         ["begin to", "start on", "embark on"], ["abandon"],
         ["set about doing something", "set about the task", "set about tackling"],
         ["Work", "Government", "Education"], ["Writing", "Speaking"], "7.5"),
    card("set aside", "C1",
         "کنار گذاشتن؛ ذخیره کردن؛ نادیده گرفتن",
         "To reserve money or time, or to ignore something temporarily.",
         "The government set aside a portion of revenue for rural clinics.",
         "دولت بخشی از درآمد را برای درمانگاه‌های روستایی کنار گذاشت.",
         ["reserve", "put aside", "set apart"], ["allocate to use"],
         ["set aside funds", "set aside time for", "should be set aside for"],
         ["Economics", "Education", "Health"], ["Reading Academic", "Writing"], "7.5"),
    card("set out", "C1",
         "شرح دادن؛ درصدد بودن؛ آغاز کردن",
         "To explain something clearly, or to begin a task.",
         "The report sets out the arguments for and against the reform.",
         "این گزارش استدلال‌های موافق و مخالف اصلاحات را شرح می‌دهد.",
         ["begin", "outline", "explain"], ["conceal"],
         ["set out to achieve", "sets out the case for", "set out the evidence"],
         ["Crime", "Research", "Education"], ["Writing", "Reading Academic"], "7.5"),
    card("shed light on", "C1",
         "روشنی انداختن بر؛ توضیح دادن",
         "To make something easier to understand.",
         "A recent study sheds light on why the treatment works.",
         "مطالعه‌ای اخیر توضیح می‌دهد که چرا این درمان مؤثر است.",
         ["clarify", "illuminate", "explain"], ["obscure"],
         ["shed light on the debate", "sheds light on why", "help shed light on"],
         ["Research", "Science", "Education"], ["Reading Academic", "Writing"], "7.5"),
    card("single out", "C1",
         "جدا کردن؛ به‌طور خاص نام بردن از",
         "To treat or mention one person differently from the others.",
         "It is unfair to single out one department for criticism.",
         "انصاف نیست که تنها یک دپارتمان را مورد انتقاد قرار دهیم.",
         ["distinguish", "isolate", "pick out"], ["generalise"],
         ["single out an individual", "singled out for praise"],
         ["Society", "Work", "Education"], ["Reading Academic", "Writing"], "7.5"),
    card("stand out", "B2",
         "برجسته بودن؛ متمایز بودن؛ به چشم آمدن",
         "To be noticeably different or better than others.",
         "Two figures stand out in the report: rural incomes and youth unemployment.",
         "دو عدد در گزارش برجسته است: درآمد روستایی و بیکاری جوانان.",
         ["be prominent", "stand out from"], ["blend in"],
         ["stand out clearly", "stands out from the rest", "one figure stands out"],
         ["Research", "Society", "Economics"], ["Writing", "Speaking"], "7.0"),
    card("stem from", "C1",
         "سرچشمه گرفتن از؛ ناشی بودن از",
         "To develop or originate from something.",
         "Much of the hostility stems from a lack of trust rather than from genuine disagreement.",
         "بخش زیادی از خصومت از فقدان اعتماد ناشی می‌شود نه از اختلاف واقعی.",
         ["derive from", "arise from", "originate from"], ["ignore"],
         ["stems from a lack of", "which stems from", "problems that stem from"],
         ["Society", "Science", "Economics"], ["Reading Academic", "Writing"], "7.5"),
    card("take account of", "C1",
         "در نظر گرفتن؛ لحاظ کردن",
         "To consider something before making a decision.",
         "The model takes account of seasonal variation rather than assuming a constant rate.",
         "این مدل تغییرات فصلی را در نظر می‌گیرد تا اینکه نرخ ثابتی فرض کند.",
         ["take into account", "consider", "allow for"], ["ignore"],
         ["takes account of costs", "must take account of", "fail to take account of"],
         ["Research", "Economics"], ["Reading Academic", "Writing"], "7.5"),
    card("take advantage of", "B2",
         "بهره‌برداری کردن از؛ استفادهٔ هوشمندانه از",
         "To make good use of an opportunity or advantage.",
         "Smaller firms were able to take advantage of the falling price of solar panels.",
         "شرکت‌های کوچک‌تر توانستند از کاهش قیمت پنل‌های خورشیدی بهره ببرند.",
         ["make use of", "exploit", "capitalise on"], ["overlook"],
         ["take full advantage of", "take advantage of the opportunity", "quick to take advantage of"],
         ["Economics", "Technology", "Work"], ["Speaking", "Writing"], "6.5"),
    dict(
        word="take into account", pos="phrasal verb", cefr="C1",
        fa="در نظر گرفتن؛ لحاظ کردن",
        en="To consider something when making a judgement or calculation.",
        ex="The policy failed to take into account how quickly habits actually change.",
        exFa="این سیاست لحاظ نکرد که عادت‌ها واقعاً با چه سرعتی تغییر می‌کنند.",
        syn=["consider", "allow for", "factor in"], ant=["disregard", "leave out"],
        coll=["take into account that", "when taking into account", "must be taken into account"],
        fam=["accountable", "accountability"],
        mistake="Do not write 'take in account'; the idiom always includes 'into'.",
        topic=["Research", "Government", "Economics"], skill=["Reading Academic", "Writing"],
        band="7.5",
    ),
    card("take on", "B2",
         "بر عهده گرفتن؛ پذیرفتن؛ شکل گرفتن",
         "To accept a responsibility, or to acquire a new quality.",
         "The role has taken on a political dimension in recent years.",
         "این نقش در سال‌های اخیر بُعدی سیاسی پیدا کرده است.",
         ["assume", "undertake", "acquire"], ["shed"],
         ["take on responsibility", "take on a new meaning", "take on staff"],
         ["Work", "Government", "Society"], ["Speaking", "Writing"], "7.0"),
    card("take over", "B2",
         "بر عهده گرفتن؛ تصاحب کردن؛ جانشین شدن",
         "To take control of an organisation, role or activity from someone else.",
         "A younger generation is gradually taking over family-run businesses.",
         "نسل جوان‌تر به‌تدریج کسب‌وکارهای خانوادگی را در اختیار می‌گیرد.",
         ["assume control of", "succeed", "inherit"], ["cede"],
         ["take over a company", "be taken over", "take over the running of"],
         ["Work", "Economics", "Family"], ["Listening Lecture", "Speaking"], "7.0"),
    card("take place", "B1",
         "رخ دادن؛ برگزار شدن؛ واقع شدن",
         "To happen, especially an event that has been arranged.",
         "The summit will take place in Nairobi next March.",
         "نشست بعدی مارس در نایروبی برگزار خواهد شد.",
         ["occur", "happen", "be held"], ["be cancelled"],
         ["take place on", "take place annually", "due to take place"],
         ["Society", "Government", "Culture"], ["Listening Lecture", "Writing"], "6.0",
         fam=["takeplace"]),
    card("take up", "B2",
         "شروع کردن به؛ مشغول شدن به؛ جذب کردن",
         "To start a new activity, or to occupy someone's time.",
         "Retirement has given her time to take up painting again.",
         "بازنشستگی به او فرصت داد تا دوباره نقاشی را از سر بگیرد.",
         ["begin", "start", "pursue"], ["abandon", "give up"],
         ["take up a hobby", "take up residence", "take up most of the time"],
         ["Health", "Family", "Work"], ["Speaking", "Listening Conversation"], "6.5"),
    card("turn down", "B2",
         "رد کردن؛ نپذیرفتن؛ کم کردن",
         "To refuse an offer or request, or to reduce the volume of something.",
         "She turned down the offer because the hours were unworkable.",
         "او پیشنهاد را رد کرد چون ساعت کاری مناسب نبود.",
         ["reject", "decline", "refuse"], ["accept"],
         ["turn down an offer", "turn down the volume", "had to turn down"],
         ["Work", "Education"], ["Speaking", "Listening Conversation"], "6.5"),
    card("turn out", "C1",
         "مشخص شدن؛ معلوم شدن؛ به نتیجه رسیدن",
         "To become known after events, or to produce a good result.",
         "The factory that everyone expected to fail turned out to be the most efficient in the region.",
         "کارخانه‌ای که انتظار می‌رفت شکست بخورد، در نهایت کارآمدترین کارخانهٔ منطقه بود.",
         ["prove to be", "transpire", "emerge"], ["remain inconclusive"],
         ["turn out to be true", "turned out badly", "turn out that"],
         ["Research", "Economics", "Society"], ["Listening Lecture", "Speaking"], "7.5"),
    card("weigh up", "C1",
         "سنجیدن؛ ارزیابی کردن؛ بررسی کردن",
         "To consider the advantages and disadvantages before deciding.",
         "Before buying a car, most drivers weigh up the cost over several years.",
         "پیش از خرید خودرو، بیشتر رانندگان هزینه را در طول چند سال ارزیابی می‌کنند.",
         ["consider", "evaluate", "assess"], ["ignore"],
         ["weigh up the options", "weigh up the risks", "carefully weighed up"],
         ["Work", "Economics", "Health"], ["Speaking", "Writing"], "7.5"),
    card("work out", "B2",
         "به نتیجه رسیدن؛ حل کردن؛ ورزش کردن",
         "To solve a problem, to succeed, or to exercise.",
         "Most students work out the correct answer once they are given a diagram.",
         "بیشتر دانشجویان به‌محض ارائهٔ یک نمودار به پاسخ درست می‌رسند.",
         ["solve", "resolve", "succeed"], ["fail"],
         ["work out a solution", "work out that", "works out well"],
         ["Education", "Science", "Health"], ["Speaking", "Writing"], "6.5"),
    card("write up", "C1",
         "ثبت کردن؛ تنظیم کردن گزارش",
         "To record something in writing, often a detailed report.",
         "The nurse wrote up her notes while the patient rested.",
         "پرستار در حالی که بیمار استراحت می‌کرد یادداشت‌هایش را می‌نوشت.",
         ["record", "document", "compile"], ["erase"],
         ["write up a report", "write up the results", "write up one's findings"],
         ["Research", "Health", "Education"], ["Listening Lecture", "Writing"], "7.0"),
]
