#!/usr/bin/env python3
"""Curated applied academic phrases for IELTS and TOEFL.

These are the topic-bound collocations that earn marks in Writing Task 2 and the
Speaking test: the noun phrases and set phrases a strong answer reaches for when
discussing education, environment, health, urbanisation, work, technology and
globalisation. They are recorded as `idiom` for the reason documented in
multiword_cards_discourse.py.
"""

from __future__ import annotations

from multiword_cards_phrasal_verbs import card


def phrase(word, cefr, fa, en, ex, ex_fa, syn, ant, coll, topic, skill, band,
          mistake=""):
    return card(word, cefr, fa, en, ex, ex_fa, syn, ant, coll, topic, skill,
                band, mistake=mistake, pos="idiom")


APPLIED = [
    phrase("a growing concern", "B2",
           "نگرانی روبه‌رشد؛ موضوع نگران‌کننده",
           "A worry that is becoming more widely felt over time.",
           "Housing costs have become a growing concern in the capital.",
           "هزینهٔ مسکن به نگرانی روبه‌رشدی در پایتخت تبدیل شده است.",
           ["an increasing worry", "a mounting concern"], ["a solved problem"],
           ["a growing concern about", "become a growing concern"],
           ["Urbanisation", "Economics", "Family"], ["Writing", "Speaking"], "7.0"),
    phrase("a growing number of", "B1",
           "شمار روزافزونی از",
           "An increasing quantity of people or things.",
           "A growing number of graduates now work abroad.",
           "شمار روزافزونی از فارغ‌التحصیلان اکنون در خارج کار می‌کنند.",
           ["an increasing number of", "more and more"], ["a decreasing number of"],
           ["a growing number of people", "a growing number of households"],
           ["Education", "Work", "Technology"], ["Writing", "Speaking"], "6.0"),
    phrase("access to education", "B2",
           "دسترسی به تحصیل؛ امکان تحصیل کردن",
           "The ability to attend school or receive formal teaching.",
           "Rural children often have limited access to education.",
           "کودکان روستایی اغلب دسترسی محدودی به تحصیل دارند.",
           ["educational access", "the availability of schooling"], ["exclusion from schooling"],
           ["ensure access to education", "limited access to education"],
           ["Education", "Society"], ["Writing", "Reading Academic"], "7.0"),
    phrase("a gap between", "B2",
           "شکاف میانِ؛ فاصلهٔ میان",
           "A difference between two groups, figures or situations.",
           "There is a widening gap between rich and poor households.",
           "شکافی رو به گسترش میان خانوارهای ثروتمند و فقیر وجود دارد.",
           ["a divide between", "a disparity between"], ["parity between"],
           ["a widening gap between", "bridge the gap between"],
           ["Economics", "Society", "Health"], ["Writing", "Speaking"], "7.0"),
    phrase("a lack of", "B1",
           "کمبودِ؛ نبودِ",
           "The state of not having enough of something.",
           "A lack of affordable housing forces many graduates to leave.",
           "کمبود مسکن قابل تومان بسیاری از فارغ‌التحصیلان را وادار به مهاجرت می‌کند.",
           ["an absence of", "a shortage of", "insufficiency of"], ["an abundance of"],
           ["a lack of funding", "due to a lack of"],
           ["Health", "Education", "Environment"], ["Writing", "Speaking"], "6.0"),
    phrase("a wide range of", "B1",
           "طیف گسترده‌ای از؛ گونه‌های بسیاری از",
           "A large and varied selection of things.",
           "The museum offers a wide range of services for school groups.",
           "موزه طیف گسترده‌ای از خدمات را برای گروه‌های مدرسه‌ای ارائه می‌دهد.",
           ["a broad range of", "a diverse selection of"], ["a narrow range of"],
           ["a wide range of options", "a wide range of subjects"],
           ["Education", "Culture", "Technology"], ["Writing", "Speaking"], "6.0"),
    phrase("on the one hand, ... on the other hand", "B2",
           "از یک طرف ... از طرف دیگر",
           "A structure that presents two contrasting points.",
           "On the one hand, remote work saves time; on the other hand, it weakens teams.",
           "از یک طرف، کار از راه دور در زمان صرفه‌جویی می‌کند؛ از طرف دیگر، تیم‌ها را تضعیف می‌کند.",
           ["firstly ... secondly", "although ... nevertheless"], [],
           ["On the one hand ... on the other hand, however"],
           ["Work", "Economics", "Society"], ["Writing", "Speaking"], "7.0"),
    phrase("sustainable development", "B2",
           "توسعهٔ پایدار",
           "Development that meets present needs without damaging future capacity.",
           "Sustainable development requires long-term planning rather than quick gains.",
           "توسعهٔ پایدار مستلزم برنامه‌ریزی بلندمدت است نه سودهای سریع.",
           ["enduring development", "responsible growth"], ["unsustainable growth"],
           ["promote sustainable development", "the goal of sustainable development"],
           ["Environment", "Economics", "Government"], ["Writing", "Reading Academic"], "7.0"),
    phrase("renewable energy", "B2",
           "انرژی تجدیدپذیر",
           "Energy from sources that are naturally replenished.",
           "Renewable energy now supplies a third of national demand.",
           "انرژی تجدیدپذیر اکنون یک‌سوم تقاضای ملی را تأمین می‌کند.",
           ["clean energy", "alternative energy"], ["fossil fuel energy"],
           ["invest in renewable energy", "shift to renewable energy"],
           ["Environment", "Energy", "Technology"], ["Writing", "Reading Academic"], "7.0"),
    phrase("carbon footprint", "C1",
           "ردپای کربنی",
           "The total greenhouse gas emissions caused by an activity or person.",
           "Reducing the carbon footprint of deliveries is now a design goal.",
           "کاهش ردپای کربنی تحویل‌ها اکنون یک هدف طراحی است.",
           ["carbon emissions", "ecological footprint"], ["zero emissions"],
           ["reduce your carbon footprint", "a smaller carbon footprint"],
           ["Environment", "Technology"], ["Writing", "Reading Academic"], "7.5"),
    phrase("public awareness", "B2",
           "آگاهی عمومی",
           "The level of knowledge that the general population has about an issue.",
           "Public awareness of recycling has grown steadily in recent years.",
           "آگاهی عمومی نسبت به بازیافت در سال‌های اخیر پیوسته رشد کرده است.",
           ["public consciousness", "public understanding"], ["public ignorance"],
           ["raise public awareness of", "greater public awareness"],
           ["Health", "Environment", "Society"], ["Writing", "Reading Academic"], "7.0"),
    phrase("raise awareness of", "B2",
           "افزایش آگاهی دربارهٔ",
           "To make people understand an issue they previously overlooked.",
           "The campaign aims to raise awareness of childhood obesity.",
           "این کمپینه هدفش افزایش آگاهی دربارهٔ چاقی کودکان است.",
           ["increase awareness of", "build awareness of"], ["obscure"],
           ["raise awareness of the dangers of", "help raise awareness of"],
           ["Health", "Environment", "Education"], ["Writing", "Speaking"], "7.0"),
    phrase("life expectancy", "B2",
           "امید به زندگی؛ متوسط طول عمر",
           "The average number of years a person is expected to live.",
           "Life expectancy in the region rose steadily over the decade.",
           "امید به زندگی در این منطقه طی یک دهه پیوسته افزایش یافت.",
           ["average lifespan", "longevity"], ["infant mortality"],
           ["average life expectancy of", "rising life expectancy"],
           ["Health", "Society"], ["Writing", "Reading Academic"], "7.0"),
    phrase("preventive healthcare", "C1",
           "مراقبت سلامت پیشگیرانه",
           "Medical care aimed at avoiding illness rather than treating it.",
           "Preventive healthcare saves far more than emergency admissions do.",
           "مراقبت سلامت پیشگیرانه بسیار بیشتر از پذیرش‌های اورژانسی صرفه‌جویی می‌کند.",
           ["preventative medicine", "prophylactic care"], ["reactive treatment"],
           ["invest in preventive healthcare", "promote preventive healthcare"],
           ["Health", "Government"], ["Writing", "Reading Academic"], "7.5"),
    phrase("an ageing population", "C1",
           "جمعیت سالخورده؛ جمعیت در حال پیری",
           "A population whose average age is rising.",
           "An ageing population places heavy pressure on pension systems.",
           "جمعیت سالخورده فشار سنگینی بر سیستم‌های بازنشستگی وارد می‌آورد.",
           ["an aging population", "an elderly population"], ["a youthful population"],
           ["an ageing population puts pressure on", "support for an ageing population"],
           ["Health", "Society", "Economics"], ["Writing", "Reading Academic"], "7.5"),
    phrase("work-life balance", "B2",
           "تعادل کار و زندگی",
           "The division of time and energy between work and personal life.",
           "Flexible hours improved work-life balance for most staff.",
           "ساعت کاری انعطاف‌پذیر تعادل کار و زندگی را برای بیشتر کارکنان بهبود داد.",
           ["work-life equilibrium", "balance between work and home"], ["work burnout"],
           ["maintain a healthy work-life balance", "struggle with work-life balance"],
           ["Work", "Health", "Family"], ["Writing", "Speaking"], "7.0"),
    phrase("job security", "B2",
           "امنیت شغلی؛ ثبات شغل",
           "The certainty that a job will continue for a long time.",
           "Young graduates are increasingly anxious about job security.",
           "فارغ‌التحصیلان جوان به‌طور فزاینده‌ای نگران امنیت شغلی هستند.",
           ["employment stability", "secure employment"], ["job insecurity", "precarious work"],
           ["lose job security", "concerns about job security"],
           ["Work", "Economics"], ["Writing", "Speaking"], "7.0"),
    phrase("vocational training", "C1",
           "آموزش فنی و حرفه‌ای",
           "Practical training that prepares someone for a specific trade.",
           "Vocational training shortened the gap between school and employment.",
           "آموزش فنی و حرفه‌ای فاصلهٔ میان مدرسه و بازار کار را کوتاه کرد.",
           ["technical training", "professional training"], ["general education"],
           ["provide vocational training", "vocational training courses"],
           ["Work", "Education"], ["Writing", "Reading Academic"], "7.5"),
    phrase("urban sprawl", "C1",
           "گسترش افقی شهر؛ پراکندگی شهری",
           "The uncontrolled outward expansion of a built-up area.",
           "Urban sprawl put pressure on farmland on the edge of the city.",
           "گسترش افقی شهر بر زمین‌های کشاورزی لبهٔ شهر فشار وارد آورد.",
           ["urban expansion", "sprawling development"], ["compact development"],
           ["control urban sprawl", "rapid urban sprawl"],
           ["Urbanisation", "Environment"], ["Reading Academic", "Writing"], "7.5"),
    phrase("population density", "C1",
           "تراکم جمعیتی",
           "The number of people living in a given area.",
           "High population density puts pressure on water supplies.",
           "تراکم بالای جمعیت بر منابع آب فشار وارد می‌آورد.",
           ["population density levels", "density of population"], ["sparse population"],
           ["high population density", "population density of the area"],
           ["Urbanisation", "Society"], ["Reading Academic", "Writing"], "7.5"),
    phrase("economic growth", "B2",
           "رشد اقتصادی",
           "An increase in the amount a country produces and earns.",
           "Economic growth slowed sharply in the second quarter.",
           "رشد اقتصادی در سه‌ماههٔ دوم به‌شدت کند شد.",
           ["economic expansion", "growth in output"], ["economic contraction", "recession"],
           ["sustainable economic growth", "rapid economic growth"],
           ["Economics", "Government"], ["Writing", "Reading Academic"], "7.0"),
    phrase("a widening inequality", "C1",
           "نابرابری فزاینده؛ شکاف رو به گسترش",
           "A growing gap between the richest and poorest groups.",
           "A widening inequality has hardened opposition to the reform.",
           "نابرابری فزاینده مخالفت با اصلاحات را سخت‌گیرانه‌تر کرده است.",
           ["a growing divide", "increasing disparity"], ["a narrowing gap"],
           ["a widening inequality between", "the growth of inequality"],
           ["Economics", "Society"], ["Writing", "Reading Academic"], "7.5"),
    phrase("digital divide", "C1",
           "شکاف دیجیتال",
           "The gap between those with reliable access to technology and those without.",
           "The digital divide widened during the shift to online teaching.",
           "شکاف دیجیتال هنگام گذار به آموزش آنلاین گسترده‌تر شد.",
           ["technology gap", "digital exclusion"], ["digital equality"],
           ["bridge the digital divide", "widen the digital divide"],
           ["Technology", "Education", "Society"], ["Writing", "Reading Academic"], "7.5"),
    phrase("artificial intelligence", "B1",
           "هوش مصنوعی",
           "Computer systems designed to perform tasks that normally need human intelligence.",
           "Artificial intelligence now handles routine customer enquiries.",
           "هوش مصنوعی اکنون به پرسش‌های معمول مشتریان رسیدگی می‌کند.",
           ["AI", "machine intelligence"], ["human judgement"],
           ["the rise of artificial intelligence", "powered by artificial intelligence"],
           ["Technology", "Work"], ["Writing", "Speaking"], "6.5"),
    phrase("screen time", "B2",
           "زمان صفحه‌نمایش؛ مدت استفاده از نمایشگر",
           "The amount of time a person spends looking at a screen.",
           "Parents are advised to limit screen time for very young children.",
           "به والدین توصیه می‌شود زمان صفحه‌نمایش کودکان بسیار خردسال را محدود کنند.",
           ["device time", "screen exposure"], [],
           ["reduce screen time", "excessive screen time"],
           ["Health", "Technology", "Family"], ["Writing", "Speaking"], "7.0"),
    phrase("academic performance", "C1",
           "عملکرد تحصیلی؛ پیشرفت درسی",
           "How well a student does in their studies.",
           "Sleep quality is closely linked to academic performance.",
           "کیفیت خواب ارتباط نزدیکی با عملکرد تحصیلی دارد.",
           ["school achievement", "educational attainment"], ["poor performance"],
           ["improve academic performance", "strong academic performance"],
           ["Education", "Health"], ["Reading Academic", "Writing"], "7.5"),
    phrase("a fair assessment", "C1",
           "ارزیابی منصفانه",
           "An evaluation based on balanced and transparent criteria.",
           "It would be a fair assessment to say that the policy has had mixed results.",
           "انصاف این است که گفته شود این سیاست نتایج دوگانه‌ای داشته است.",
           ["an even-handed evaluation", "a balanced judgement"], ["a biased assessment"],
           ["a fair assessment of", "a fair assessment would be"],
           ["Education", "Society"], ["Writing", "Speaking"], "7.5"),
    phrase("crime rate", "B2",
           "نرخ جرم؛ آمار بزهکاری",
           "The number of crimes recorded in a given area and period.",
           "The crime rate fell for the third consecutive year.",
           "نرخ جرم برای سومین سال متوالی کاهش یافت.",
           ["incidence of crime", "offence figures"], ["crime wave"],
           ["a falling crime rate", "the city's crime rate"],
           ["Crime", "Society"], ["Reading Academic", "Speaking"], "7.0"),
    phrase("deterrent effect", "C1",
           "اثر بازدارنده",
           "The way a punishment discourages further offending.",
           "The deterrent effect of the fine is almost nil for repeat offenders.",
           "اثر بازدارندهٔ جریمه برای تکرارکنندگان تقریباً ناچیز است.",
           ["deterrence", "a preventive effect"], ["incentive effect"],
           ["have a deterrent effect", "the deterrent effect of punishment"],
           ["Crime", "Government"], ["Reading Academic", "Writing"], "7.5"),
    phrase("welfare state", "C1",
           "دولت رفاه",
           "A system in which the government supports citizens through grants and services.",
           "The welfare state reduced poverty but raised the tax burden.",
           "دولت رفاه فقر را کاهش داد اما بار مالیاتی را افزایش داد.",
           ["social welfare system", "the benefits system"], ["free market"],
           ["expand the welfare state", "pressure on the welfare state"],
           ["Society", "Economics", "Government"], ["Reading Academic", "Writing"], "7.5"),
    phrase("mass media", "B1",
           "رسانه‌های جمعی؛ رسانه‌های گروهی",
           "Media that reach very large audiences, such as television and newspapers.",
           "Mass media shape public opinion more than personal contact does.",
           "رسانه‌های جمعی بیش از تماس شخصی افکار عمومی را شکل می‌دهند.",
           ["the media", "mainstream media"], ["social media"],
           ["the influence of mass media", "through mass media"],
           ["Media", "Society", "Culture"], ["Reading Academic", "Speaking"], "6.5"),
    phrase("advertising campaigns", "B2",
           "کمپین‌های تبلیغاتی",
           "Organised series of advertisements promoting a product or idea.",
           "Advertising campaigns now target users rather than products.",
           "کمپین‌های تبلیغاتی اکنون به‌جای محصول، کاربر را هدف می‌گیرند.",
           ["promotional campaigns", "marketing campaigns"], ["public information"],
           ["launch an advertising campaign", "targeted advertising campaigns"],
           ["Media", "Advertising", "Culture"], ["Reading Academic", "Speaking"], "7.0"),
    phrase("cultural heritage", "B2",
           "میراث فرهنگی",
           "The traditions, buildings and practices passed down from earlier generations.",
           "Flood damage destroyed centuries of cultural heritage.",
           "خسارت سیل قرن‌ها میراث فرهنگی را نابود کرد.",
           ["heritage", "a cultural legacy"], ["modern development"],
           ["protect cultural heritage", "lost cultural heritage"],
           ["Culture", "Tourism", "Environment"], ["Reading Academic", "Writing"], "7.0"),
    phrase("cultural identity", "C1",
           "هویت فرهنگی",
           "A shared sense of belonging to a particular culture.",
           "Minority communities often negotiate a delicate cultural identity.",
           "جوامع اقلیت اغلب هویتی فرهنگی شکننده را مذاکره می‌کنند.",
           ["collective identity", "national identity"], ["cultural assimilation"],
           ["preserve cultural identity", "a shared cultural identity"],
           ["Culture", "Globalisation", "Society"], ["Writing", "Speaking"], "7.5"),
    phrase("a melting pot", "C1",
           "دیگ آبگوشت؛ جایگاه آمیختگی فرهنگ‌ها",
           "A place where many different peoples and cultures live together.",
           "The port city has long been a melting pot of sailors and traders.",
           "بندرگاه مدت‌ها دیگ آبگوشت ملوانان و تاجران بوده است.",
           ["a cultural crossroads", "a place of diversity"], ["a homogenous community"],
           ["remain a melting pot", "as a cultural melting pot"],
           ["Culture", "Globalisation"], ["Speaking", "Writing"], "7.5"),
    phrase("a vicious cycle", "C1",
           "چرخهٔ معیوب؛ دور باطل",
           "A repeating pattern in which each problem worsens the next.",
           "Debt and low income form a vicious cycle for many households.",
           "بدهی و درآمد پایین چرخه‌ای معیوب برای بسیاری از خانواده‌ها می‌سازد.",
           ["a vicious circle", "a self-perpetuating cycle"], ["a virtuous cycle"],
           ["create a vicious cycle", "trap households in a vicious cycle"],
           ["Economics", "Society", "Family"], ["Speaking", "Writing"], "7.5"),
    phrase("a fair test", "B1",
           "آزمایش منصفانه؛ سنجش عادلانه",
           "A test in which all participants are treated identically.",
           "It would be a fair test only if both groups used the same equipment.",
           "تنها در صورتی آزمایش منصفانه است که هر دو گروه از تجهیزات یکسان استفاده کنند.",
           ["a controlled trial", "a neutral trial"], ["a biased test"],
           ["provide a fair test of", "only a fair test if"],
           ["Research", "Science", "Education"], ["Listening Lecture", "Speaking"], "7.0"),
    phrase("statistical significance", "C1",
           "معناداری آماری",
           "The likelihood that a result is not due to chance alone.",
           "The effect showed statistical significance but was very small.",
           "این اثر از نظر آماری معنادار بود اما بسیار کوچک بود.",
           ["significance level", "a significant p-value"], ["an insignificant result"],
           ["reach statistical significance", "below the threshold of statistical significance"],
           ["Research", "Science"], ["Reading Academic", "Listening Lecture"], "8.0"),
    phrase("a control group", "C1",
           "گروه شاهد؛ گروه کنترل",
           "A comparison group that receives no treatment.",
           "Each trial compared the drug with a control group of placebos.",
           "هر آزمایش دارو را با یک گروه شاهد از دارونماها مقایسه کرد.",
           ["comparison group", "the control arm"], ["the treatment group"],
           ["a randomised control group", "compared with a control group"],
           ["Research", "Health", "Science"], ["Reading Academic", "Listening Lecture"], "7.5"),
    phrase("a significant proportion", "C1",
           "نسبت قابل توجهی؛ بخش چشمگیری",
           "A share that is large enough to matter statistically.",
           "A significant proportion of the sample had never visited a clinic.",
           "نسبت قابل توجهی از نمونه هرگز به درمانگاه مراجعه نکرده بود.",
           ["a substantial share", "a sizeable fraction"], ["a negligible proportion"],
           ["a significant proportion of X", "account for a significant proportion"],
           ["Research", "Health", "Society"], ["Reading Academic", "Writing"], "7.5"),
    phrase("the underlying cause", "C1",
           "علت زیربنایی؛ دلیل اصلی",
           "The fundamental reason behind an observed effect.",
           "Researchers were asked to identify the underlying cause of the failure.",
           "از پژوهشگران خواسته شد علت زیربنایی شکست را شناسایی کنند.",
           ["the root cause", "the fundamental driver"], ["the immediate trigger"],
           ["identify the underlying cause of", "an underlying cause for"],
           ["Research", "Health", "Crime"], ["Reading Academic", "Writing"], "7.5"),
    phrase("a marked increase", "B1",
           "افزایش چشمگیر؛ رشد محسوس",
           "A rise that is clearly noticeable.",
           "The figures show a marked increase in waste since 2019.",
           "ارقام از سال ۲۰۱۹ افزایش چشمگیری در پسماند نشان می‌دهند.",
           ["a sharp increase", "a pronounced rise"], ["a slight increase"],
           ["a marked increase in X", "record a marked increase"],
           ["Health", "Economics", "Environment"], ["Reading Academic", "Writing"], "7.0"),
    phrase("a sharp rise", "B2",
           "افزایش تند؛ رشد ناگهانی",
           "A fast and large increase over a short period.",
           "There was a sharp rise in demand after the announcement.",
           "پس از اعلام خبر، افزایش تندی در تقاضا رخ داد.",
           ["a steep increase", "a sudden rise"], ["a gradual decline"],
           ["a sharp rise in prices", "a sharp rise in unemployment"],
           ["Economics", "Health", "Urbanisation"], ["Reading Academic", "Writing"], "7.0"),
    phrase("a gradual decline", "B2",
           "کاهش تدریجی؛ افول آرام",
           "A slow decrease over a long period.",
           "The report records a gradual decline in birth rates.",
           "این گزارش کاهش تدریجی نرخ زادگان را ثبت می‌کند.",
           ["a steady decrease", "a slow decline"], ["a sharp increase"],
           ["a gradual decline in X", "come into gradual decline"],
           ["Society", "Economics", "Environment"], ["Reading Academic", "Writing"], "7.0"),
    phrase("a viable alternative", "C1",
           "جایگزین عملی؛ گزینهٔ شدنی",
           "An option that can actually work in practice.",
           "Cycling is a viable alternative for short journeys.",
           "دوچرخه‌سواری جایگزین عملی برای سفرهای کوتاه است.",
           ["a workable option", "a feasible choice"], ["an impractical proposal"],
           ["a viable alternative to", "prove a viable alternative"],
           ["Transport", "Environment", "Economics"], ["Writing", "Speaking"], "7.5"),
    phrase("a fair assessment of", "C1",
           "سنجش منصفانهٔ",
           "An even-handed evaluation of performance or quality.",
           "The panel published a fair assessment of each proposal.",
           "کمیته ارزیابی منصفانه‌ای از هر پیشنهاد منتشر کرد.",
           ["an impartial review of", "a balanced evaluation of"], ["a partisan account of"],
           ["a fair assessment of X", "provide a fair assessment of"],
           ["Education", "Society"], ["Reading Academic", "Writing"], "7.5"),
    phrase("the onset of", "C1",
           "آغازِ؛ شروعِ",
           "The moment when something such as a condition begins.",
           "The onset of the illness was sudden in most cases.",
           "آغاز بیماری در بیشتر موارد ناگهانی بود.",
           ["the beginning of", "the start of"], ["the end of"],
           ["the onset of the disease", "with the onset of"],
           ["Health", "Environment", "Economics"], ["Reading Academic", "Writing"], "7.5"),
    phrase("a growing body of research", "C1",
           "بدنهٔ روزافزون پژوهش",
           "An expanding collection of studies on a subject.",
           "A growing body of research links the two factors closely.",
           "بدنه‌ای روزافزون از پژوهش‌ها این دو عامل را به‌شدت مرتبط می‌داند.",
           ["an expanding literature", "accumulating research"], ["a single study"],
           ["a growing body of research suggests", "supported by a growing body of research"],
           ["Research", "Health", "Science"], ["Reading Academic", "Writing"], "7.5"),
    phrase("a downward trend", "B2",
           "روند نزولی؛ جهت کاهش",
           "A general movement towards lower values.",
           "The data show a clear downward trend over the period.",
           "داده‌ها روند نزولی روشنی را در این بازه نشان می‌دهند.",
           ["a declining pattern", "a falling trend"], ["an upward trend"],
           ["a downward trend in X", "show a downward trend"],
           ["Economics", "Health", "Society"], ["Reading Academic", "Writing"], "7.0"),
    phrase("a trade-off", "C1",
           "مصالحه؛ بده‌بستان",
           "A situation where gaining one thing means giving up another.",
           "There is a clear trade-off between speed and accuracy.",
           "مصالحهٔ روشنی میان سرعت و دقت وجود دارد.",
           ["a compromise", "an exchange of gains", "a balance"], ["a free lunch"],
           ["involve a trade-off", "an unavoidable trade-off between"],
           ["Economics", "Science", "Work"], ["Writing", "Speaking"], "7.5"),
    phrase("on the contrary", "C1",
           "برعکسِ؛ در واقع برخلاف",
           "Used to state the opposite of what was just said.",
           "The drug did not reduce symptoms; on the contrary, it increased them.",
           "این دارو علائم را کاهش نداد؛ برعکس، آن‌ها را افزایش داد.",
          ["in fact", "on the other hand", "conversely"], ["accordingly"],
          ["on the contrary, however", "quite the contrary"],
          ["Science", "Society"], ["Writing", "Speaking"], "7.5"),
    phrase("be attributed to", "C1",
           "نسبت داده شدن به؛ منتسب بودن به",
           "To be explained as the result of a particular cause.",
           "The decline has been attributed to a single failed harvest.",
           "این کاهش به یک محصول ناموفق نسبت داده شده است.",
           ["be ascribed to", "be put down to", "be explained by"], ["be caused by no known factor"],
           ["be attributed to a cause", "largely attributed to"],
           ["Research", "Science", "Health"], ["Reading Academic", "Writing"], "7.5"),
    phrase("be associated with", "B2",
           "همبسته بودن با؛ مرتبط بودن با",
           "To happen together with something, without proving cause.",
           "Poor sleep is associated with lower exam scores.",
           "خواب نامناسب با نمرات پایین‌تر همبسته است.",
           ["be linked to", "come with", "be connected to"], ["be unrelated to"],
           ["be strongly associated with", "closely associated with"],
           ["Health", "Research", "Education"], ["Reading Academic", "Writing"], "7.0"),
    phrase("be responsible for", "B1",
           "مسئول بودنِ؛ باعث بودنِ",
           "To be the cause of something, or to be in charge of a duty.",
           "Overfishing is responsible for most of the decline in stocks.",
           "ماهیگیری بیش از حد مسئول بیشتر کاهش ذخایر ماهی است.",
           ["be accountable for", "cause", "be in charge of"], ["be blameless for"],
           ["be responsible for the loss", "hold responsible for"],
           ["Environment", "Crime", "Work"], ["Reading Academic", "Writing"], "6.5"),
    phrase("be committed to", "C1",
           "متعهد بودن به؛ پایبند بودن به",
           "To be strongly dedicated to a course of action.",
           "The agency is committed to reducing waiting times by a fifth.",
           "این نهاد متعهد است زمان انتظار را به میزان یک‌پنجم کاهش دهد.",
           ["be dedicated to", "be bound to", "pledge oneself to"], ["be indifferent to"],
           ["be committed to doing", "firmly committed to"],
           ["Government", "Health", "Work"], ["Reading Academic", "Writing"], "7.5"),
    phrase("be subject to", "C1",
           "مشمولِ؛ تابعِ؛ در معرضِ",
           "To be under the authority or influence of something.",
           "All new buildings are now subject to energy standards.",
           "همهٔ ساختمان‌های جدید اکنون تابع استانداردهای انرژی هستند.",
           ["be governed by", "be answerable to", "be exposed to"], ["be exempt from"],
           ["be subject to scrutiny", "be subject to approval"],
           ["Government", "Crime", "Science"], ["Reading Academic", "Writing"], "7.5"),
    phrase("be engaged in", "C1",
           "مشغول بودن به؛ درگیر بودن در",
           "To be involved in an activity or process.",
           "Most adults are engaged in some form of paid work.",
           "بیشتر بزرگسالان به نوعی کار با مزد مشغول هستند.",
           ["be involved in", "be occupied with", "participate in"], ["abstain from"],
           ["be engaged in research", "actively engaged in"],
           ["Work", "Education", "Society"], ["Reading Academic", "Writing"], "7.5"),
    phrase("be exposed to", "B1",
           "در معرضِ؛ مواجه بودن با",
           "To be introduced to something harmful or to a particular influence.",
           "Infants can be exposed to second-hand smoke when parents smoke indoors.",
           "شیرخواران در صورتی که والدین در داخل خانه سیگار بکشند در معرض دود دست‌دوم قرار می‌گیرند.",
           ["be subject to", "encounter", "come into contact with"], ["be shielded from"],
           ["be heavily exposed to", "be exposed to radiation"],
           ["Health", "Environment", "Media"], ["Reading Academic", "Writing"], "7.0"),
    phrase("be entitled to", "C1",
           "مستحقِ بودن؛ حق داشتن به",
           "To have a legal or moral right to something.",
           "Every resident is entitled to free emergency care.",
           "هر ساکن حق دریافت خدمات اورژانسی رایگان را دارد.",
           ["have the right to", "be eligible for"], ["be barred from"],
           ["be entitled to free", "legally entitled to"],
           ["Health", "Crime", "Society"], ["Reading Academic", "Writing"], "7.5"),
    phrase("be inclined to", "C1",
           "مایل بودن به؛ متمایل به",
           "To be likely to do something or to hold a view.",
           "Few reviewers are inclined to trust self-reported data.",
           "تعداد اندکی از داوران مایل‌اند به داده‌های خوداظهاری اعتماد کنند.",
           ["be willing to", "tend to", "be predisposed to"], ["be determined to"],
           ["be inclined to agree", "inclined to believe"],
           ["Science", "Research", "Society"], ["Reading Academic", "Writing"], "7.5"),
    phrase("be reluctant to", "B2",
           "تمایل نداشتن به؛ از انجام چیزی دلگیر بودن",
           "To be unwilling to do something.",
           "Firms are often reluctant to share data that reveals weak sales.",
           "شرکت‌ها اغلب تمایلی ندارند داده‌هایی را که فروش ضعیف را نشان می‌دهد به اشتراک بگذارند.",
           ["be unwilling to", "be hesitant about"], ["be eager to"],
           ["be reluctant to admit", "remain reluctant to"],
           ["Work", "Society"], ["Speaking", "Writing"], "7.0"),
    phrase("be vulnerable to", "C1",
           "آسیب‌پذیر در برابرِ؛ در معرض خطرِ",
           "To be easily harmed or attacked.",
           "Low-lying districts are especially vulnerable to flooding.",
           "مناطق پستی به‌ویژه در معرض سیل آسیب‌پذیرند.",
           ["be at risk from", "be exposed to", "be defenceless against"], ["be immune to"],
           ["be vulnerable to attack", "particularly vulnerable to"],
           ["Health", "Environment", "Crime"], ["Reading Academic", "Writing"], "7.5"),
]
