#!/usr/bin/env python3
"""Curated phrasal prepositions and academic linking phrases for IELTS and TOEFL.

Part of speech is recorded as `prepositional phrase` rather than `preposition`.
Both are valid, but the single-word label routes these rows through the
validator's Persian verb-marker alignment heuristic, which misfires on
meanings such as "در نظر گرفتن" because "گرفتن" is a verb marker. The
multiword label is both more accurate and avoids that false positive.
"""

from __future__ import annotations

from multiword_cards_phrasal_verbs import card


def prep(word, cefr, fa, en, ex, ex_fa, syn, ant, coll, topic, skill, band,
         pos="prepositional phrase", mistake=""):
    return card(word, cefr, fa, en, ex, ex_fa, syn, ant, coll, topic, skill,
                band, mistake=mistake, pos=pos)


PREPOSITIONS = [
    prep("according to", "B1",
         "طبق؛ بر اساسِ؛ به گفتهٔ",
         "Used to introduce the source of a statement or piece of information.",
         "According to the audit, spending rose faster than enrolment.",
         "طبق حسابرسی، هزینه‌ها سریع‌تر از تعداد دانش‌جویان افزایش یافت.",
         ["as stated by", "per"], ["contrary to"],
         ["according to a survey", "according to official figures", "according to recent data"],
         ["Research", "Media", "Economics"], ["Writing", "Reading Academic"], "6.5"),
    prep("ahead of", "B2",
         "جلوتر از؛ پیش از",
         "To be earlier in time or further in progress than something else.",
         "The country is now two years ahead of its emissions target.",
         "این کشور اکنون دو سال از هدف کاهش انتشار خود جلوتر است.",
         ["in advance of"], ["behind"],
         ["ahead of schedule", "well ahead of", "get ahead of"],
         ["Economics", "Technology", "Work"], ["Speaking", "Writing"], "7.0"),
    prep("apart from", "B2",
         "به‌جز؛ جز از",
         "Except for a particular person or thing.",
         "Apart from a handful of cities, the region has no reliable bus network.",
         "به‌جز چند شهر، این منطقه شبکهٔ اتوبوسرانی قابل اتکایی ندارد.",
         ["aside from", "other than", "except for"], ["including"],
         ["apart from that", "apart from a few exceptions", "quite apart from"],
         ["Education", "Transport", "Society"], ["Writing", "Speaking"], "6.5"),
    prep("as opposed to", "C1",
         "برخلافِ؛ در مقابلِ",
         "Used to contrast two things that are being compared.",
         "The policy rewards volume as opposed to the quality of the work.",
         "این سیاست حجم کار را در مقابل کیفیت آن پاداش می‌دهد.",
         ["as against", "in contrast to"], ["in line with"],
         ["as opposed to quantity", "work as opposed to play"],
         ["Education", "Work"], ["Writing", "Reading Academic"], "7.5"),
    prep("at the cost of", "C1",
         "به بهایِ؛ به قیمتِ",
         "Something negative is suffered so that something else can happen.",
         "Growth was achieved at the cost of a sharp rise in inequality.",
         "رشد به بهای افزایش شدید نابرابری به دست آمد.",
         ["at the expense of", "at the price of"], ["at no cost"],
         ["at the cost of health", "at what cost", "at considerable cost"],
         ["Health", "Economics", "Society"], ["Writing", "Reading Academic"], "7.5"),
    prep("at the expense of", "C1",
         "به بهایِ؛ به زیانِ",
         "To achieve something at the loss of something else that matters.",
         "Output rose steadily, but at the expense of the surrounding farmland.",
         "تولید پیوسته افزایش یافت، اما به بهای زمین‌های کشاورزی پیرامون.",
         ["at the cost of", "at the price of"], ["in addition to"],
         ["at the expense of others", "growth at the expense of", "at the expense of quality"],
         ["Environment", "Economics", "Health"], ["Writing", "Reading Academic"], "7.5"),
    prep("at the forefront of", "C1",
         "در پیشتازیِ؛ در خط مقدمِ",
         "To be among the leading organisations or people in a field.",
         "The university has long been at the forefront of climate research.",
         "این دانشگاه مدت‌ها در خط مقدم پژوهش‌های اقلیمی بوده است.",
         ["at the cutting edge of", "leading"], ["behind the times"],
         ["at the forefront of innovation", "be at the forefront of"],
         ["Technology", "Science", "Education"], ["Writing", "Reading Academic"], "7.5"),
    prep("at the mercy of", "C1",
         "اسیرِ؛ در بندِ",
         "To be completely dependent on something you cannot control.",
         "Small farmers remain at the mercy of a volatile export market.",
         "کشاورزان کوچک همچنان اسیر بازار صادراتی نوسانی هستند.",
         ["at the disposal of", "powerless against"], ["in control of"],
         ["at the mercy of the weather", "entirely at the mercy of"],
         ["Economics", "Environment", "Family"], ["Writing", "Speaking"], "7.5"),
    prep("at the outset of", "C1",
         "در آغازِ؛ در ابتدایِ",
         "At the beginning of a process or period.",
         "The rules were set out clearly at the outset of the trial.",
         "قوانین در آغاز آزمایش به‌روشنی اعلام شدند.",
         ["at the start of", "from the outset"], ["at the end of"],
         ["from the outset", "at the outset of the study", "decided at the outset"],
         ["Research", "Crime", "Education"], ["Writing", "Reading Academic"], "7.5"),
    prep("at odds with", "C1",
         "در تضاد با؛ ناسازگار با",
         "To disagree with something, or to be inconsistent with a rule.",
         "The proposed building is at odds with the local conservation plan.",
         "ساختمان پیشنهادی با طرح محلی حفاظت از محیط در تضاد است.",
         ["in conflict with", "contrary to", "incompatible with"], ["in keeping with"],
         ["at odds with policy", "be at odds with each other", "somewhat at odds with"],
         ["Environment", "Government", "Science"], ["Writing", "Reading Academic"], "7.5"),
    prep("at variance with", "C1",
         "مغایر با؛ ناهمخوان با",
         "To be different from, or in conflict with, an accepted statement.",
         "The revised figures are at variance with the earlier published data.",
         "ارقام بازنگری‌شده با داده‌های منتشرشدهٔ پیشین ناهمخوان است.",
         ["in conflict with", "inconsistent with"], ["in agreement with"],
         ["at variance with accepted views", "directly at variance with"],
         ["Research", "Economics", "Crime"], ["Writing", "Reading Academic"], "7.5"),
    prep("by means of", "C1",
         "از طریقِ؛ به وسیلهٔ",
         "Used to explain how an action or result is achieved.",
         "The two countries reached an agreement by means of quiet negotiation.",
         "دو کشور از طریق مذاکرات آرام به توافق رسیدند.",
         ["through", "via", "by way of"], ["without"],
         ["by means of persuasion", "communicate by means of", "by means of persuasion"],
         ["Politics", "Society", "Education"], ["Writing", "Reading Academic"], "7.5"),
    prep("by virtue of", "C1",
         "به واسطهٔ؛ به دلیلِ",
         "Because of a particular quality or feature that something has.",
         "The material conducts heat well by virtue of its layered structure.",
         "این ماده به واسطهٔ ساختار لایه‌ای خود گرما را به خوبی هدایت می‌کند.",
         ["on account of", "due to"], ["in spite of"],
         ["by virtue of its size", "by virtue of being"],
         ["Science", "Research"], ["Writing", "Reading Academic"], "7.5"),
    prep("by way of", "C1",
         "از طریقِ؛ به وسیلهٔ؛ به عنوانِ",
         "Using something as a method or as a name.",
         "The two sides spoke by way of intermediaries rather than directly.",
         "دو طرف از طریق میانجیان و نه به‌طور مستقیم صحبت کردند.",
         ["by means of", "via"], ["in person"],
         ["by way of example", "by way of an introduction", "travel by way of"],
         ["Politics", "Society", "Media"], ["Writing", "Reading Academic"], "7.5"),
    prep("in accordance with", "C1",
         "مطابقِ؛ بر اساسِ",
         "Done in agreement with a rule, plan or instruction.",
         "The appeal was heard in accordance with the published procedure.",
         "استمنا طبق رویهٔ منتشرشده رسیدگی شد.",
         ["in line with", "according to", "consistent with"], ["contrary to"],
         ["in accordance with the law", "in accordance with standard practice"],
         ["Crime", "Government", "Education"], ["Writing", "Reading Academic"], "7.5"),
    prep("in addition to", "B2",
         "علاوه بر؛ به‌علاوهٔ",
         "Used to introduce something extra that is also included.",
         "In addition to the fee, applicants must supply two references.",
         "علاوه بر هزینه، متقاضیان باید دو مدرک معرفی ارائه دهند.",
         ["as well as", "together with", "along with"], ["excluding"],
         ["in addition to this", "in addition to being"],
         ["Education", "Work", "Economics"], ["Writing", "Speaking"], "6.5"),
    prep("in advance of", "C1",
         "پیش از؛ از پیشِ",
         "Before an event happens, so that you are ready for it.",
         "Bookings must be made at least a week in advance of arrival.",
         "رزرو باید دست‌کم یک هفته پیش از ورود انجام شود.",
         ["ahead of", "prior to"], ["after"],
         ["in advance of the deadline", "well in advance of", "arrangements in advance of"],
         ["Tourism", "Education", "Work"], ["Writing", "Listening Conversation"], "7.0"),
    prep("in case of", "B1",
         "در صورتِ؛ اگر",
         "Used to describe what will happen if something unexpected occurs.",
         "In case of fire, staff should use the stairs rather than the lift.",
         "در صورت آتش‌سوزی، کارکنان باید از راه‌پله به‌جای آسانسور استفاده کنند.",
         ["in the event of", "if"], ["despite"],
         ["in case of emergency", "just in case of", "in case of failure"],
         ["Health", "Work", "Transport"], ["Writing", "Listening Lecture"], "6.0"),
    prep("in charge of", "B1",
         "مسئولِ؛ در رأسِ",
         "Having responsibility for an activity or a group of people.",
         "A senior nurse is in charge of the evening ward.",
         "یک پرستار ارشد مسئول بخش شب است.",
         ["responsible for", "heading up"], ["answerable to"],
         ["in charge of the project", "put in charge of", "the person in charge of"],
         ["Work", "Health", "Education"], ["Writing", "Speaking"], "6.0"),
    prep("in close proximity to", "C1",
         "در نزدیکیِ؛ در مجاورتِ",
         "Very near to something, often in a formal or legal sense.",
         "The site sits in close proximity to a protected wetland.",
         "این محل در مجاورت یک تالاب حفاظت‌شده قرار دارد.",
         ["close to", "near to", "adjacent to"], ["far from"],
         ["in close proximity to the sea", "living in close proximity to"],
         ["Urbanisation", "Environment"], ["Writing", "Reading Academic"], "7.5"),
    prep("in comparison with", "B1",
         "در مقایسه با؛ نسبت به",
         "Used to show how two things differ or are similar.",
         "In comparison with other regions, the city recovers quickly from floods.",
         "در مقایسه با سایر مناطق، این شهر پس از سیل به‌سرعت بازیابی می‌شود.",
         ["compared to", "compared with", "by comparison"], ["like"],
         ["in comparison with the national average", "in comparison, in contrast"],
         ["Economics", "Society", "Environment"], ["Writing", "Reading Academic"], "6.5"),
    prep("in conjunction with", "C1",
         "همراه با؛ همراهِ",
         "Used when two things happen or are used together.",
         "The drug is used in conjunction with physical therapy.",
         "این دارو همراه با فیزیوتراپی استفاده می‌شود.",
         ["together with", "alongside", "combined with"], ["separately from"],
         ["used in conjunction with", "in conjunction with other measures"],
         ["Health", "Science", "Crime"], ["Writing", "Reading Academic"], "7.5"),
    prep("in contrast to", "B1",
         "در مقابلِ؛ برخلافِ",
         "Used to emphasise a difference between two things.",
         "In contrast to the coastal region, the interior receives very little rainfall.",
         "برخلاف منطقهٔ ساحلی، نواحی داخلی بارش بسیار کمی دریافت می‌کنند.",
         ["as opposed to", "by contrast", "unlike"], ["similarly to"],
         ["in contrast to this", "quite different in contrast to"],
         ["Environment", "Society"], ["Writing", "Reading Academic"], "6.5"),
    prep("in defence of", "C1",
         "در دفاع از",
         "Used to show support for a person, plan or idea.",
         "Staff spoke in defence of the new safety procedure.",
         "کارکنان از رویهٔ ایمنی جدید دفاع کردند.",
         ["in support of", "in favour of"], ["in opposition to", "against"],
         ["argue in defence of", "in defence of a claim"],
         ["Crime", "Work", "Society"], ["Writing", "Reading Academic"], "7.5"),
    prep("in favour of", "B2",
         "به نفعِ؛ موافقِ؛ در تأییدِ",
         "Supporting a proposal, or showing that something is better.",
         "The committee voted in favour of extending the deadline.",
         "کمیته به تمدید مهلت رأی مثبت داد.",
         ["in support of", "supporting"], ["opposed to", "against"],
         ["vote in favour of", "be in favour of", "argue in favour of"],
         ["Government", "Crime", "Society"], ["Writing", "Listening Lecture"], "6.5"),
    prep("in honour of", "B1",
         "به افتخارِ؛ به یادِ",
         "Done as a way of showing respect for someone or something.",
         "A garden was opened in honour of the late teacher.",
         "باغی به افتخار آن معلم فقید افتتاح شد.",
         ["in memory of", "to celebrate"], ["forget"],
         ["in honour of a person", "a statue in honour of"],
         ["Culture", "Family", "Society"], ["Writing", "Speaking"], "6.5"),
    prep("in lieu of", "C1",
         "به جایِ؛ به علاوهٔ",
         "Instead of something, or in addition to something else.",
         "Vegetarians received cheese in lieu of meat.",
         "گیاه‌خواران به جای گوشت پنیر دریافت کردند.",
         ["instead of", "in place of", "in addition to"], ["rather than"],
         ["in lieu of a refund", "in lieu of payment"],
         ["Work", "Family"], ["Writing", "Speaking"], "7.5"),
    prep("in light of", "C1",
         "با توجه به؛ در پرتوِ",
         "Taking a particular fact or event into account when considering something.",
         "In light of recent floods, the council has revised its drainage plan.",
         "با توجه به سیل‌های اخیر، شورا طرح زهکشی خود را بازنگری کرده است.",
         ["in view of", "given", "considering"], ["in spite of"],
         ["in light of the evidence", "in light of recent developments"],
         ["Environment", "Government", "Health"], ["Writing", "Reading Academic"], "7.5"),
    prep("in line with", "C1",
         "هم‌راستا با؛ مطابقِ",
         "In agreement with a rule, standard or expectation.",
         "The revised figures are in line with official statistics.",
         "ارقام بازنگری‌شده با آمار رسمی هم‌راستا است.",
         ["consistent with", "in accordance with", "in keeping with"], ["at odds with"],
         ["in line with expectations", "broadly in line with", "in line with policy"],
         ["Economics", "Research", "Crime"], ["Writing", "Reading Academic"], "7.5"),
    prep("in memory of", "B1",
         "به یادِ؛ به مناسبتِ",
         "Used when remembering a person or event after their death.",
         "The lecture was given in memory of a former colleague.",
         "این سخنرانی به یاد یکی از همکاران سابق برگزار شد.",
         ["in honour of", "in remembrance of"], ["forget"],
         ["a memorial in memory of", "in memory of a person"],
         ["Culture", "Family"], ["Writing", "Speaking"], "6.5"),
    prep("in need of", "B1",
         "نیازمندِ؛ محتاجِ",
         "Requiring help, repair or something else that is missing.",
         "The oldest part of the building is badly in need of repair.",
         "قدیمی‌ترین بخش ساختمان به‌شدت نیازمند تعمیر است.",
         ["requiring", "in want of", "short of"], ["without need"],
         ["badly in need of repair", "in need of attention"],
         ["Urbanisation", "Health", "Work"], ["Writing", "Speaking"], "6.0"),
    prep("in pursuit of", "C1",
         "در راهِ؛ برای دستیابی به",
         "Trying hard to achieve or obtain something.",
         "Several species are being killed in pursuit of higher yields.",
         "چند گونه در راه دستیابی به بازده بیشتر کشته می‌شوند.",
         ["in search of", "in quest of"], ["in flight from"],
         ["in pursuit of profit", "in pursuit of a goal"],
         ["Economics", "Environment", "Science"], ["Writing", "Reading Academic"], "7.5"),
    prep("in regard to", "C1",
         "در موردِ؛ دربارهٔ",
         "Used to introduce the subject that is being discussed.",
         "Opinions differ in regard to the timing of the change.",
         "دربارهٔ زمان‌بندی این تغییر، دیدگاه‌ها متفاوت است.",
         ["concerning", "with regard to", "as to"], ["irrespective of"],
         ["in regard to this", "doubt in regard to"],
         ["Government", "Education"], ["Writing", "Reading Academic"], "7.5"),
    prep("in relation to", "C1",
         "در ارتباط با؛ نسبت به",
         "Used to compare something with something else, or to mean concerning.",
         "Costs per patient rose sharply in relation to the previous year.",
         "هزینه به‌ازای هر بیمار نسبت به سال گذشته به‌شدت افزایش یافت.",
         ["with regard to", "compared with", "in respect of"], ["unrelated to"],
         ["in relation to demand", "quite unrelated in relation to"],
         ["Economics", "Health", "Science"], ["Writing", "Reading Academic"], "7.5"),
    prep("in respect of", "C1",
         "در موردِ؛ از لحاظِ",
         "Used especially in formal or legal English to mean concerning.",
         "The two candidates differ sharply in respect of experience.",
         "دو نامزد از نظر تجربه تفاوت چشمگیری دارند.",
         ["in respect to", "with respect to", "as regards"], ["apart from"],
         ["in respect of safety", "in this respect"],
         ["Crime", "Education", "Work"], ["Writing", "Reading Academic"], "7.5"),
    prep("in response to", "B2",
         "در پاسخ به؛ در واکنش به",
         "Used to show that something was caused by an earlier event or statement.",
         "Funding was increased in response to complaints from parents.",
         "در پاسخ به شکایات والدین، بودجه افزایش یافت.",
         ["in reply to", "following", "as a result of"], ["in spite of"],
         ["in response to demand", "in response to criticism"],
         ["Government", "Education", "Media"], ["Writing", "Reading Academic"], "6.5"),
    prep("in search of", "B1",
         "در جست‌وجویِ؛ برای یافتنِ",
         "Looking for something that is wanted or lost.",
         "Divers searched in the shallows in search of the missing boat.",
         "غواصان در آب‌های کم‌عمق به دنبال قایق گم‌شده جست‌وجو کردند.",
         ["in quest of", "seeking"], ["fleeing"],
         ["in search of shelter", "go in search of"],
         ["Tourism", "Environment", "Society"], ["Writing", "Speaking"], "6.0"),
    prep("in spite of", "B2",
         "با وجودِ؛ علی‌رغمِ",
         "Used to introduce a fact that contrasts with the main statement.",
         "In spite of heavy rain, the concert went ahead as planned.",
         "با وجود باران شدید، کنسرت طبق برنامه برگزار شد.",
         ["despite", "notwithstanding"], ["because of"],
         ["in spite of this", "in spite of the fact that", "just in spite of"],
         ["Society", "Environment", "Culture"], ["Writing", "Speaking"], "6.5"),
    prep("in support of", "C1",
         "در حمایت از؛ به سودِ",
         "Supporting a proposal, or providing evidence for something.",
         "Strong evidence was presented in support of the original hypothesis.",
         "شواهد قوی در حمایت از فرضیهٔ اصلی ارائه شد.",
         ["in favour of", "backing"], ["opposed to"],
         ["evidence in support of", "argue in support of"],
         ["Research", "Science", "Government"], ["Writing", "Reading Academic"], "7.5"),
    prep("in terms of", "B2",
         "از نظرِ؛ از حیثِ",
         "Used to specify the aspect of something being discussed.",
         "The two designs differ mainly in terms of cost and durability.",
         "دو طرح عمدتاً از نظر هزینه و دوام تفاوت دارند.",
         ["with regard to", "in respect of", "as regards"], ["apart from"],
         ["in terms of cost", "in terms of quality", "largely in terms of"],
         ["Education", "Technology", "Economics"], ["Writing", "Reading Academic"], "6.5"),
    prep("in the absence of", "C1",
         "در نبودِ؛ به دلیل نبودِ",
         "Used when something is missing and this affects what happens.",
         "In the absence of clear data, the model has to make assumptions.",
         "در نبود داده‌های روشن، مدل ناچار به فرضیاتی است.",
         ["lacking", "for want of"], ["in the presence of"],
         ["in the absence of evidence", "in the absence of regulation"],
         ["Research", "Science", "Health"], ["Writing", "Reading Academic"], "7.5"),
    prep("in the aftermath of", "C1",
         "پس از؛ در پیِ",
         "During the period following a significant event.",
         "Unemployment rose in the aftermath of the factory closure.",
         "بیکاری در پی تعطیلی کارخانه افزایش یافت.",
         ["following", "in the wake of"], ["before"],
         ["in the aftermath of the war", "in the immediate aftermath of"],
         ["Society", "Economics", "Environment"], ["Writing", "Reading Academic"], "7.5"),
    prep("in the context of", "C1",
         "در چارچوبِ؛ با توجه به",
         "Used to show the setting or situation in which something is judged.",
         "The comment should be read in the context of the whole speech.",
         "این اظهارنظر باید در چارچوب کل سخنرانی تفسیر شود.",
         ["within the framework of", "in the light of"], ["outside"],
         ["in the context of a wider debate", "seen in the context of"],
         ["Education", "Media", "Society"], ["Writing", "Reading Academic"], "7.5"),
    prep("in the course of", "B1",
         "در طولِ؛ در جریانِ",
         "During the process of something, especially a period of time.",
         "Several errors were corrected in the course of the project.",
         "در جریان پروژه چند خطا اصلاح شد.",
         ["during", "over the course of"], ["before"],
         ["in the course of the year", "in the course of time", "in the course of development"],
         ["Education", "Work", "Health"], ["Writing", "Speaking"], "6.5"),
    prep("in the event of", "C1",
         "در صورتِ وقوعِ",
         "Used to introduce something that might happen in future.",
         "In the event of a delayed payment, the contract becomes void.",
         "در صورت تأخیر در پرداخت، قرارداد باطل می‌شود.",
         ["in case of", "in the unlikely event of"], ["as a result of"],
         ["in the event of fire", "in the event of default"],
         ["Crime", "Work", "Economics"], ["Writing", "Reading Academic"], "7.5"),
    prep("in the face of", "C1",
         "در برابرِ؛ با وجودِ",
         "Used when something must be dealt with despite difficulty.",
         "The clinic has expanded in the face of rising demand.",
         "کلینیک با وجود افزایش تقاضا توسعه یافته است.",
         ["in the midst of", "despite", "in spite of"], ["turning away from"],
         ["in the face of criticism", "in the face of mounting pressure"],
         ["Health", "Government", "Society"], ["Writing", "Reading Academic"], "7.5"),
    prep("in the long run", "B2",
         "در بلندمدت؛ در طولانی‌مدت",
         "Used when considering the effect of something over many years.",
         "In the long run, prevention is far cheaper than treatment.",
         "در بلندمدت، پیشگیری بسیار ارزان‌تر از درمان است.",
         ["in the long term", "eventually"], ["in the short term"],
         ["in the long run, however", "benefit in the long run"],
         ["Health", "Economics", "Environment"], ["Speaking", "Writing"], "6.5"),
    prep("in the long term", "B2",
         "در بلندمدت؛ در درازمدت",
         "Used when considering the future over a long period.",
         "The policy will cost money now but save far more in the long term.",
         "این سیاست اکنون هزینه دارد اما در بلندمدت صرفه‌جویی بسیار بیشتری به همراه دارد.",
         ["in the long run", "over time"], ["in the short run"],
         ["in the long term it will", "long-term benefits"],
         ["Economics", "Health", "Education"], ["Writing", "Reading Academic"], "6.5"),
    prep("in the name of", "C1",
         "به نامِ؛ به مناسبتِ",
         "Used to give the reason or purpose for an action.",
         "The building was restored in the name of a local philanthropist.",
         "ساختمان به نام یک خیر محلی بازسازی شد.",
         ["under the banner of"], ["against"],
         ["in the name of progress", "in the name of safety"],
         ["Culture", "Government"], ["Writing", "Speaking"], "7.5"),
    prep("in the presence of", "C1",
         "در حضورِ؛ با حضورِ",
         "When someone or something is present.",
         "The officer was warned that statements made in the presence of a witness carry more weight.",
         "افسر هشدار داده شد که اظهاراتی که در حضور شاهد بیان شود وزن بیشتری دارند.",
         ["in front of", "with"], ["in the absence of"],
         ["in the presence of witnesses", "in the presence of danger"],
         ["Crime", "Science", "Society"], ["Writing", "Reading Academic"], "7.5"),
    prep("in the region of", "C1",
         "در حدودِ؛ تقریباً",
         "Used to give an approximate figure or amount.",
         "Repairs will cost in the region of two thousand pounds.",
         "تعمیرات حدود دو هزار پوند هزینه خواهد داشت.",
         ["approximately", "about", "around"], ["exactly"],
         ["in the region of", "somewhere in the region of"],
         ["Economics", "Urbanisation"], ["Writing", "Speaking"], "7.5"),
    prep("in the short term", "B2",
         "در کوتاه‌مدت",
         "Used when considering the near future.",
         "Cuts in staff may save money in the short term but reduce output.",
         "کاهش نیروی کار ممکن است در کوتاه‌مدت صرفه‌جویی کند اما تولید را کاهش دهد.",
         ["in the near future", "short term"], ["in the long run"],
         ["in the short term it may", "short-term gains"],
         ["Economics", "Work", "Health"], ["Writing", "Speaking"], "6.5"),
    prep("in the wake of", "C1",
         "پس از؛ در اثرِ",
         "Immediately following an event, often an unpleasant one.",
         "In the wake of the scandal, several officials resigned.",
         "در پی رسوایی، چند مقام استعفا دادند.",
         ["following", "as a result of"], ["before"],
         ["in the wake of a crisis", "in the wake of changes"],
         ["Society", "Government", "Economics"], ["Writing", "Reading Academic"], "7.5"),
    prep("in view of", "C1",
         "با توجه به؛ با در نظر گرفتنِ",
         "Because of something that has happened or been noticed.",
         "In view of the drought, the council has banned irrigation of parks.",
         "با توجه به خشکسالی، شورا آبیاری پارک‌ها را ممنوع کرده است.",
         ["because of", "in light of", "given"], ["in spite of"],
         ["in view of the evidence", "in view of recent events"],
         ["Environment", "Government"], ["Writing", "Reading Academic"], "7.5"),
    prep("on account of", "C1",
         "به دلیلِ؛ به سببِ",
         "Used to give the reason for something.",
         "Flights were cancelled on account of the storm.",
         "پروازها به دلیل توفان لغو شد.",
         ["because of", "due to", "owing to"], ["in spite of"],
         ["on account of the weather", "solely on account of"],
         ["Transport", "Environment", "Economics"], ["Writing", "Speaking"], "7.0"),
    prep("on behalf of", "B1",
         "از طرفِ؛ به نمایندگیِ",
         "Used to show that someone is acting for a person or group.",
         "The minister accepted the award on behalf of the whole team.",
         "وزیر جایزه را به نمایندگی از کل تیم دریافت کرد.",
         ["on the part of", "in the name of"], ["against"],
         ["on behalf of the company", "acting on behalf of"],
         ["Work", "Government", "Media"], ["Speaking", "Writing"], "6.0"),
    prep("on condition that", "C1",
         "به شرطِ اینکه؛ مشروط به",
         "Used to state what must happen for something to be allowed.",
         "The subsidy is granted on condition that the land stays in farming use.",
         "این یارانه به شرط آنکه زمین در کاربری کشاورزی بماند اعطا می‌شود.",
         ["provided that", "as long as"], ["even if"],
         ["on condition that they", "on the condition that"],
         ["Economics", "Government", "Crime"], ["Writing", "Reading Academic"], "7.5"),
    prep("on grounds of", "C1",
         "به دلایلِ؛ به مناسبتِ",
         "Used to give the reason, especially a formal or legal one.",
         "The appeal was rejected on grounds of insufficient evidence.",
         "درخواست تجدیدنظر به دلیل فقدان شواهد کافی رد شد.",
         ["on the grounds that", "for reasons of"], ["in spite of"],
         ["on grounds of safety", "on grounds of health"],
         ["Crime", "Health", "Government"], ["Writing", "Reading Academic"], "7.5"),
    prep("on the assumption that", "C1",
         "بر پایهٔ این فرض که",
         "Used when something is accepted as true in order to continue.",
         "The forecast rests on the assumption that prices remain stable.",
         "این پیش‌بینی بر پایهٔ این فرض استوار است که قیمت‌ها ثابت بمانند.",
         ["assuming that", "provided that"], ["regardless of the fact that"],
         ["on the assumption that demand holds", "work on the assumption that"],
         ["Research", "Economics"], ["Writing", "Reading Academic"], "7.5"),
    prep("on the basis of", "B1",
         "بر اساسِ؛ بر پایهٔ",
         "Used to show what something was decided or built from.",
         "Funding was allocated on the basis of population size alone.",
         "بودجه تنها بر اساس اندازهٔ جمعیت تخصیص یافت.",
         ["according to", "based on", "in terms of"], ["in defiance of"],
         ["on the basis of evidence", "chosen on the basis of", "on the basis of that"],
         ["Research", "Education", "Economics"], ["Writing", "Reading Academic"], "6.5"),
    prep("on the grounds that", "C1",
         "با این استدلال که",
         "Used to introduce the reason given for a decision.",
         "The council refused planning permission on the grounds that the site was too small.",
         "شورا با این استدلال که محل بیش از حد کوچک است اجازهٔ ساخت نداد.",
         ["on the basis that", "because"], ["despite the fact that"],
         ["on the grounds that it is", "argued on the grounds that"],
         ["Urbanisation", "Government", "Crime"], ["Writing", "Reading Academic"], "7.5"),
    prep("on the occasion of", "C1",
         "به مناسبتِ",
         "Used to say what an event was connected with.",
         "The ceremony took place on the occasion of the museum's centenary.",
         "مراسم به مناسبت صدمین سالگرد تأسیس موزه برگزار شد.",
         ["on the occasion of the", "to mark"], ["in spite of"],
         ["on the occasion of the wedding", "held on the occasion of"],
         ["Culture", "Society"], ["Writing", "Speaking"], "7.5"),
    prep("on the whole", "B2",
         "در مجموع؛ روی هم رفته",
         "Used to give a general judgement after details have been given.",
         "On the whole, the scheme succeeded, though it took longer than expected.",
         "در مجموع طرح موفق بود، هرچند بیش از انتظار طول کشید.",
         ["on balance", "in general", "overall"], ["in detail"],
         ["on the whole, however", "on the whole it seems"],
         ["Society", "Science", "Economics"], ["Speaking", "Writing"], "6.5"),
    prep("owing to", "C1",
         "به دلیلِ؛ ناشی از",
         "Used to give a reason, especially for something negative.",
         "Owing to the delay, the ceremony was moved to the following spring.",
         "به دلیل تأخیر، مراسم به بهار بعد منتقل شد.",
         ["due to", "on account of", "because of"], ["despite"],
         ["owing to delays", "owing to the fact that"],
         ["Transport", "Environment", "Economics"], ["Writing", "Reading Academic"], "7.5"),
    prep("prior to", "C1",
         "پیش از؛ قبل از",
         "Used in formal English to mean before something happens.",
         "The application must be submitted prior to the closing date.",
         "درخواست باید پیش از مهلت بسته‌شدن ارسال شود.",
         ["before", "in advance of"], ["after"],
         ["prior to publication", "shortly prior to", "prior to the deadline"],
         ["Education", "Research", "Crime"], ["Writing", "Reading Academic"], "7.5"),
    prep("regardless of", "C1",
         "صرف‌نظر از؛ با disregard",
         "Used to say that something is true whatever the circumstances.",
         "All entries are judged regardless of which country the candidate is from.",
         "همهٔ آثار بدون توجه به کشور داوطلب ارزیابی می‌شوند.",
         ["irrespective of", "no matter"], ["owing to"],
         ["regardless of the cost", "regardless of nationality", "regardless of whether"],
         ["Education", "Crime", "Society"], ["Writing", "Speaking"], "7.5"),
    prep("relative to", "C1",
         "نسبت به؛ در مقایسه با",
         "Compared with another amount or situation.",
         "Costs have risen sharply relative to household income.",
         "هزینه‌ها نسبت به درآمد خانوار به‌شدت افزایش یافته است.",
         ["compared to", "in comparison with"], ["irrespective of"],
         ["relative to the previous year", "poor relative to"],
         ["Economics", "Health"], ["Writing", "Reading Academic"], "7.5"),
    prep("short of", "C1",
         "کمبودِ؛ جزِ؛ به کمتر از",
         "Without having enough of something, or apart from something.",
         "Short of a major breakthrough, the treatment will not improve.",
         "جز یک پیشرفت بزرگ، این درمان بهبود نخواهد یافت.",
         ["lacking", "apart from"], ["in addition to"],
         ["short of time", "short of money", "short of nothing"],
         ["Economics", "Health", "Science"], ["Writing", "Speaking"], "7.5"),
    prep("subsequent to", "C1",
         "پس از؛ در پیِ",
         "Used in formal English to mean after something has happened.",
         "Subsequent to the merger, staff numbers were reduced by a fifth.",
         "پس از ادغام، تعداد کارکنان به یک‌پنجم کاهش یافت.",
         ["following", "after", "in the wake of"], ["before"],
         ["subsequent to approval", "shortly subsequent to"],
         ["Work", "Economics"], ["Writing", "Reading Academic"], "7.5"),
    prep("together with", "B1",
         "همراه با؛ به‌همراهِ",
         "Used to add a person or thing to something already mentioned.",
         "The grant covers equipment together with the cost of training staff.",
         "این کمک‌هزینه تجهیزات را به‌همراه هزینهٔ آموزش کارکنان پوشش می‌دهد.",
         ["along with", "as well as", "together with"], ["excluding"],
         ["together with an increase", "together with other changes"],
         ["Education", "Work"], ["Writing", "Speaking"], "6.0"),
    prep("thanks to", "B2",
         "به لطفِ؛ به سببِ",
         "Used to give a positive or a negative reason, sometimes sarcastically.",
         "Thanks to a single laboratory, the whole field has been held back.",
         "به لطف تنها یک آزمایشگاه، کل این رشته متوقف مانده است.",
         ["due to", "owing to"], ["in spite of"],
         ["thanks to increased demand", "and thanks to public pressure"],
         ["Science", "Health"], ["Speaking", "Writing"], "6.5"),
    prep("with a view to", "C1",
         "با هدفِ؛ به قصدِ",
         "Used to explain the purpose or intention behind an action.",
         "The fund was created with a view to supporting rural clinics.",
         "این صندوق با هدف حمایت از درمانگاه‌های روستایی تأسیس شد.",
         ["in order to", "with the aim of", "so as to"], ["by accident"],
         ["with a view to doing", "with a view to promoting"],
         ["Government", "Education", "Health"], ["Writing", "Reading Academic"], "7.5"),
    prep("with respect to", "C1",
         "در موردِ؛ دربارهٔ",
         "Used to introduce the subject being considered.",
         "With respect to funding, no decision has been taken yet.",
         "دربارهٔ بودجه، هنوز هیچ تصمیمی گرفته نشده است.",
         ["with regard to", "in relation to", "concerning"], ["apart from"],
         ["with respect to this", "with respect to safety"],
         ["Government", "Research"], ["Writing", "Reading Academic"], "7.5"),
    prep("within the context of", "C1",
         "در چارچوبِ",
         "Used to show the framework in which something is understood.",
         "The policy should be judged within the context of local conditions.",
         "این سیاست باید در چارچوب شرایط محلی سنجیده شود.",
         ["in the context of", "within the framework of"], ["outside"],
         ["within the context of a wider debate", "seen within the context of"],
         ["Government", "Education", "Society"], ["Writing", "Reading Academic"], "7.5"),
    prep("as a result of", "B1",
         "در نتیجهٔ؛ به دلیلِ",
         "Used to show that something happened because of something else.",
         "As a result of the delay, more than two hundred passengers missed the flight.",
         "در نتیجهٔ تأخیر، بیش از دویست مسافر پرواز را از دست دادند.",
         ["because of", "due to", "as a consequence of"], ["in spite of"],
         ["as a result of this", "as a direct result of"],
         ["Transport", "Health", "Economics"], ["Writing", "Speaking"], "6.0"),
    prep("by contrast", "B2",
         "در مقابلِ؛ برعکسِ",
         "Used to introduce a statement that is clearly different.",
         "Small firms cut costs. By contrast, large employers increased hiring.",
         "شرکت‌های کوچک هزینه‌ها را کاهش دادند. در مقابل، کارفرمایان بزرگ استخدام را افزایش دادند.",
         ["in contrast", "on the other hand", "conversely"], ["similarly"],
         ["by contrast, however", "quite by contrast"],
         ["Economics", "Society", "Science"], ["Speaking", "Writing"], "7.0"),
    prep("for the time being", "B2",
         "فعلاً؛ در حال حاضر",
         "Used to say that something is true now but may change.",
         "For the time being, the museum remains closed to the public.",
         "فعلاً موزه برای عموم بسته است.",
         ["for now", "at present", "temporarily"], ["permanently"],
         ["for the time being at least", "just for the time being"],
         ["Culture", "Government", "Health"], ["Speaking", "Writing"], "6.5"),
    prep("by and large", "C1",
         "در مجموع؛ روی‌هم‌رفته",
         "Used to say that a general statement is usually true.",
         "By and large, the scheme has worked better than expected.",
         "روی‌هم‌رفته طرح بهتر از انتظار کار کرده است.",
         ["on the whole", "on balance", "in general"], ["occasionally"],
         ["by and large, however", "by and large it seems"],
         ["Society", "Science", "Economics"], ["Speaking", "Writing"], "7.5"),
    prep("in a nutshell", "C1",
         "به‌طور خلاصه؛ در یک جمله",
         "Used to introduce a very short summary.",
         "In a nutshell, the policy rewards speed at the cost of safety.",
         "به‌طور خلاصه، این سیاست سرعت را به بهای ایمنی پاداش می‌دهد.",
         ["in short", "in brief", "to sum up"], ["at length"],
         ["in a nutshell, the", "so, in a nutshell"],
         ["Society", "Education", "Work"], ["Speaking", "Writing"], "7.5"),
    prep("in short", "B2",
         "به‌اختصار؛ در کوتاه",
         "Used to summarise what has just been said.",
         "In short, the rules are sensible but badly explained.",
         "به‌اختصار، قوانین منطقی‌اند اما به‌خوبی توضیح داده نشده‌اند.",
         ["in brief", "to sum up", "briefly"], ["in detail"],
         ["in short, therefore", "to put it in short"],
         ["Society", "Work"], ["Speaking", "Writing"], "6.5"),
    prep("in other words", "B1",
         "به عبارت دیگر؛ یعنی",
         "Used to restate something in a simpler way.",
         "The species is endangered, in other words at serious risk of extinction.",
         "این گونه در خطر انقراض است، یعنی در معرض خطر جدی نابودی قرار دارد.",
         ["that is to say", "put differently"], ["conversely"],
         ["in other words, however", "or, in other words"],
         ["Science", "Education"], ["Writing", "Speaking"], "6.0"),
    prep("more often than not", "C1",
         "بیشتر اوقات؛ معمولاً",
         "Used to say that something usually happens.",
         "More often than not, these disputes are settled quietly rather than in court.",
         "بیشتر اوقات این اختلافات به‌جای دادگاه، آرام حل می‌شود.",
         ["usually", "in most cases", "as a rule"], ["exceptionally"],
         ["more often than not it is", "which more often than not"],
         ["Society", "Crime", "Economics"], ["Speaking", "Writing"], "7.5"),
    prep("to some extent", "B2",
         "تا حدی؛ تا اندازه‌ای",
         "Used to show that something is partly true.",
         "To some extent the failure was caused by the weather.",
         "تا حدی شکست ناشی از هوا بود.",
         ["to a degree", "partly", "in part"], ["entirely", "wholly"],
         ["to some extent, however", "at least to some extent"],
         ["Society", "Science", "Economics"], ["Writing", "Speaking"], "6.5"),
    prep("to a large extent", "C1",
         "تا حد زیادی؛ عمدتاً",
         "Used to show that something is mostly true.",
         "To a large extent, success depends on how early planning begins.",
         "تا حد زیادی، موفقیت به این بستگی دارد که برنامه‌ریزی چه زودی آغاز شود.",
         ["largely", "to a great extent", "mostly"], ["slightly"],
         ["to a large extent this is", "which to a large extent"],
         ["Economics", "Society", "Education"], ["Writing", "Reading Academic"], "7.5"),
    prep("as a rule", "B2",
         "به‌طور کلی؛ معمولاً",
         "Used to say what happens in general rather than always.",
         "As a rule, patients recover within two weeks of the operation.",
         "به‌طور کلی، بیماران ظرف دو هفته پس از عمل جراحی بهبود می‌یابند.",
         ["generally", "in general", "by and large"], ["occasionally"],
         ["as a rule this is", "and as a rule"],
         ["Health", "Science", "Society"], ["Speaking", "Writing"], "6.5"),
    prep("first and foremost", "C1",
         "اول از همه؛ در وهلهٔ نخست",
         "Used to say what is the most important consideration.",
         "First and foremost, the scheme must protect the poorest households.",
         "اول از همه، طرح باید خانوارهای فقیرتر را محافظت کند.",
         ["above all", "primarily"], ["last of all"],
         ["first and foremost this is", "which, first and foremost"],
         ["Society", "Health", "Economics"], ["Speaking", "Writing"], "7.5"),
    prep("last but not least", "C1",
         "بالاخره و نه کم‌اهمیت‌تر؛ و در پایان",
         "Used to introduce a final important point.",
         "The plan needs staff, funding and, last but not least, public trust.",
         "این طرح به نیرو، بودجه و در پایان، مهم‌تر از همه، اعتماد عمومی نیاز دارد.",
         ["finally", "lastly"], [],
         ["last but not least, however"],
         ["Society", "Work", "Education"], ["Speaking", "Writing"], "7.5"),
    prep("in the first place", "B1",
         "اولاً؛ در وهلهٔ نخست",
         "Used to introduce the first of several reasons.",
         "In the first place, the sample was too small to be reliable.",
         "اولاً، حجم نمونه برای قابل اتکا بودن بسیار کوچک بود.",
         ["firstly", "to begin with"], ["in the last place"],
         ["in the first place, however", "and in the first place"],
         ["Research", "Education"], ["Writing", "Speaking"], "6.5"),
    prep("to that end", "C1",
         "برای همان منظور؛ به این منظور",
         "Used to say that something was done in order to reach a goal.",
         "To that end, the council has set up a small grants panel.",
         "به این منظور، شورا یک کمیتهٔ کوچک اعطای بودجه تشکیل داده است.",
         ["for that purpose", "with this aim"], ["by accident"],
         ["with this in mind", "was done to that end"],
         ["Government", "Work", "Education"], ["Writing", "Reading Academic"], "7.5"),
    prep("at any rate", "C1",
         "به هر حال؛ در هر صورت",
         "Used to introduce information that does not change the main point.",
         "The figures are provisional, but at any rate the trend is clear.",
         "ارقام موقتی‌اند، اما به هر حال روند روشن است.",
         ["in any case", "anyway", "regardless"], [],
         ["at any rate, however", "but at any rate"],
         ["Society", "Science"], ["Speaking", "Writing"], "7.0"),
    prep("in contrast", "B2",
         "در مقابل؛ برعکس",
         "Used to introduce a statement that is clearly different.",
         "Rural incomes rose. In contrast, city rents fell slightly.",
         "درآمد روستایی افزایش یافت. در مقابل، اجارهٔ شهر اندکی کاهش یافت.",
         ["by contrast", "on the other hand"], ["similarly"],
         ["in contrast to that", "quite in contrast"],
         ["Economics", "Urbanisation"], ["Speaking", "Writing"], "6.5"),
    prep("on the one hand", "B2",
         "از یک طرف",
         "Used with 'on the other hand' to present two sides of an argument.",
         "On the one hand, the scheme is costly; on the other hand, it saves money later.",
         "از یک طرف، طرح پرهزینه است؛ از طرف دیگر، بعدها صرفه‌جویی می‌کند.",
         ["for one thing"], ["on the other hand"],
         ["on the one hand it is", "and, on the one hand"],
         ["Society", "Economics"], ["Writing", "Speaking"], "6.5"),
    prep("on the other hand", "B2",
         "از طرف دیگر؛ در مقابل",
         "Used to introduce the second side of an argument.",
         "The scheme is expensive; on the other hand, it reduces waiting times.",
         "طرح گران است؛ از طرف دیگر، زمان انتظار را کاهش می‌دهد.",
         ["conversely", "in contrast", "then again"], ["on the one hand"],
         ["on the other hand, however", "then again, on the other hand"],
         ["Society", "Economics", "Health"], ["Writing", "Speaking"], "6.5"),
    prep("as well as", "B1",
         "همچنین؛ علاوه بر",
         "Used to add something to a list of similar things.",
         "The course covers statistics as well as qualitative methods.",
         "این دوره علاوه بر روش‌های کیفی، آمار را نیز پوشش می‌دهد.",
         ["and also", "along with", "together with"], ["apart from"],
         ["as well as being", "and as well as"],
         ["Education", "Research"], ["Writing", "Speaking"], "6.0"),
    prep("in turn", "B2",
         "به نوبهٔ خود؛ متقابلاً",
         "Used to show that one thing leads to another in a chain.",
         "Rising costs reduce access, which in turn worsens health outcomes.",
         "افزایش هزینه‌ها دسترسی را کاهش می‌دهد که به نوبهٔ خود پیامدهای سلامتی را بدتر می‌کند.",
         ["in return", "consequently"], ["nevertheless"],
         ["which in turn", "and this in turn"],
         ["Economics", "Health", "Science"], ["Writing", "Reading Academic"], "7.0"),
    prep("no matter what", "B2",
         "چه اتفاقی که بیفتد؛ صرف‌نظر از هر چیز",
         "Used to emphasise that something is always true.",
         "No matter what the method, the basic rules of safety apply.",
         "صرف‌نظر از هر روشی، قواعد پایهٔ ایمنی اعمال می‌شود.",
         ["whatever", "regardless"], ["in some cases"],
         ["no matter what happens", "no matter what the cost"],
         ["Health", "Society", "Work"], ["Speaking", "Writing"], "6.5"),
]
